#ifndef RC_H
#define RC_H

// rc.h
// 7/15/2011

#define RC_PREFIX_IMAGE ":/images/"
#define RC_IMAGE_NULL   ""

#define RC_PREFIX_TR    ":/tr/"
#define RC_TR_NULL      ""

// - Translations -

#define RC_TR_EN        RC_PREFIX_TR "tr_en"
#define RC_TR_JA        RC_PREFIX_TR "tr_ja"
#define RC_TR_ZH        RC_PREFIX_TR "tr_zh"
#define RC_TR_TW        RC_TR_ZH

// - Apps -

#define RC_IMAGE_APP    RC_PREFIX_IMAGE "app.png"

// - Buttons -
#define RC_IMAGE_PLAY_HOVER     RC_PREFIX_IMAGE "play.png"
#define RC_IMAGE_PLAY           RC_PREFIX_IMAGE "play_hover.png"        // Highlight play button
#define RC_IMAGE_PLAY_PRESSED   RC_PREFIX_IMAGE "play_pressed.png"
#define RC_IMAGE_PLAY_DISABLED  RC_PREFIX_IMAGE "play_disabled.png"
#define RC_IMAGE_PLAY_CHECKED   RC_PREFIX_IMAGE "play_checked.png"
#define RC_IMAGE_PLAY_CHECKED_HOVER RC_IMAGE_PLAY_HOVER
#define RC_IMAGE_STOP           RC_PREFIX_IMAGE "stop.png"
#define RC_IMAGE_STOP_HOVER     RC_PREFIX_IMAGE "stop_hover.png"
#define RC_IMAGE_STOP_PRESSED   RC_PREFIX_IMAGE "stop_pressed.png"
#define RC_IMAGE_STOP_DISABLED  RC_PREFIX_IMAGE "stop_disabled.png"
#define RC_IMAGE_STOP_CHECKED   RC_PREFIX_IMAGE "stop_checked.png"
#define RC_IMAGE_STOP_CHECKED_HOVER RC_IMAGE_STOP_HOVER
#define RC_IMAGE_PAUSE          RC_PREFIX_IMAGE "pause.png"
#define RC_IMAGE_PAUSE_HOVER    RC_PREFIX_IMAGE "pause_hover.png"
#define RC_IMAGE_PAUSE_PRESSED  RC_PREFIX_IMAGE "pause_pressed.png"
#define RC_IMAGE_PAUSE_DISABLED RC_PREFIX_IMAGE "pause_disabled.png"
#define RC_IMAGE_PAUSE_CHECKED  RC_PREFIX_IMAGE "pause_checked.png"
#define RC_IMAGE_PAUSE_CHECKED_HOVER RC_IMAGE_PAUSE_HOVER
#define RC_IMAGE_OPEN           RC_PREFIX_IMAGE "open.png"
#define RC_IMAGE_OPEN_HOVER     RC_PREFIX_IMAGE "open_hover.png"
#define RC_IMAGE_OPEN_PRESSED   RC_PREFIX_IMAGE "open_pressed.png"
#define RC_IMAGE_OPEN_DISABLED  RC_PREFIX_IMAGE "open_disabled.png"
#define RC_IMAGE_OPEN_CHECKED   RC_PREFIX_IMAGE "open_checked.png"
#define RC_IMAGE_OPEN_CHECKED_HOVER RC_IMAGE_OPEN_HOVER
#define RC_IMAGE_NEXTFRAME              RC_PREFIX_IMAGE "nextframe.png"
#define RC_IMAGE_NEXTFRAME_HOVER        RC_PREFIX_IMAGE "nextframe_hover.png"
#define RC_IMAGE_NEXTFRAME_PRESSED      RC_PREFIX_IMAGE "nextframe_pressed.png"
#define RC_IMAGE_NEXTFRAME_DISABLED     RC_PREFIX_IMAGE "nextframe_disabled.png"
#define RC_IMAGE_NEXTFRAME_CHECKED      RC_PREFIX_IMAGE "nextframe_checked.png"
#define RC_IMAGE_NEXTFRAME_CHECKED_HOVER RC_IMAGE_NEXTFRAME_HOVER
#define RC_IMAGE_MINI           RC_PREFIX_IMAGE "mini.png"
#define RC_IMAGE_MINI_HOVER     RC_PREFIX_IMAGE "mini_hover.png"
#define RC_IMAGE_MINI_PRESSED   RC_PREFIX_IMAGE "mini_pressed.png"
#define RC_IMAGE_MINI_DISABLED  RC_PREFIX_IMAGE "mini_disabled.png"
#define RC_IMAGE_MINI_CHECKED   RC_PREFIX_IMAGE "mini_checked.png"
#define RC_IMAGE_MINI_CHECKED_HOVER RC_IMAGE_MINI_HOVER
#define RC_IMAGE_LIVE           RC_PREFIX_IMAGE "live.png"
#define RC_IMAGE_LIVE_HOVER     RC_PREFIX_IMAGE "live_hover.png"
#define RC_IMAGE_LIVE_PRESSED   RC_PREFIX_IMAGE "live_pressed.png"
#define RC_IMAGE_LIVE_DISABLED  RC_PREFIX_IMAGE "live_disabled.png"
#define RC_IMAGE_LIVE_CHECKED   RC_PREFIX_IMAGE "live_checked.png"
#define RC_IMAGE_LIVE_CHECKED_HOVER RC_IMAGE_LIVE_HOVER
#define RC_IMAGE_SYNC           RC_PREFIX_IMAGE "sync.png"
#define RC_IMAGE_SYNC_HOVER     RC_PREFIX_IMAGE "sync_hover.png"
#define RC_IMAGE_SYNC_PRESSED   RC_PREFIX_IMAGE "sync_pressed.png"
#define RC_IMAGE_SYNC_DISABLED  RC_PREFIX_IMAGE "sync_disabled.png"
#define RC_IMAGE_SYNC_CHECKED   RC_PREFIX_IMAGE "sync_checked.png"
#define RC_IMAGE_SYNC_CHECKED_HOVER RC_IMAGE_SYNC_HOVER
#define RC_IMAGE_FULLSCREEN             RC_PREFIX_IMAGE "fullscreen.png"
#define RC_IMAGE_FULLSCREEN_HOVER       RC_PREFIX_IMAGE "fullscreen_hover.png"
#define RC_IMAGE_FULLSCREEN_PRESSED     RC_PREFIX_IMAGE "fullscreen_pressed.png"
#define RC_IMAGE_FULLSCREEN_DISABLED    RC_PREFIX_IMAGE "fullscreen_disabled.png"
#define RC_IMAGE_FULLSCREEN_CHECKED     RC_PREFIX_IMAGE "fullscreen_checked.png"
#define RC_IMAGE_FULLSCREEN_CHECKED_HOVER RC_IMAGE_FULLSCREEN_HOVER
#define RC_IMAGE_ANNOT                  RC_PREFIX_IMAGE "comment.png"
#define RC_IMAGE_ANNOT_HOVER            RC_PREFIX_IMAGE "comment_hover.png"
#define RC_IMAGE_ANNOT_PRESSED          RC_PREFIX_IMAGE "comment_pressed.png"
#define RC_IMAGE_ANNOT_DISABLED         RC_PREFIX_IMAGE "comment_disabled.png"
#define RC_IMAGE_ANNOT_CHECKED          RC_PREFIX_IMAGE "comment_checked.png"
#define RC_IMAGE_ANNOT_CHECKED_HOVER RC_IMAGE_ANNOT_HOVER
#define RC_IMAGE_SHOWANNOT              RC_IMAGE_ANNOT_HOVER
#define RC_IMAGE_SHOWANNOT_HOVER        RC_IMAGE_ANNOT
#define RC_IMAGE_SHOWANNOT_PRESSED      RC_IMAGE_ANNOT_PRESSED
#define RC_IMAGE_SHOWANNOT_DISABLED     RC_IMAGE_ANNOT_DISABLED
#define RC_IMAGE_SHOWANNOT_CHECKED      RC_IMAGE_ANNOT_CHECKED
#define RC_IMAGE_SHOWANNOT_CHECKED_HOVER RC_IMAGE_SHOWANNOT_HOVER
#define RC_IMAGE_HIDEANNOT              RC_IMAGE_ANNOT
#define RC_IMAGE_HIDEANNOT_HOVER        RC_IMAGE_ANNOT_HOVER
#define RC_IMAGE_HIDEANNOT_PRESSED      RC_IMAGE_ANNOT_PRESSED
#define RC_IMAGE_HIDEANNOT_DISABLED     RC_IMAGE_ANNOT_DISABLED
#define RC_IMAGE_HIDEANNOT_CHECKED      RC_IMAGE_ANNOT_CHECKED
#define RC_IMAGE_HIDEANNOT_CHECKED_HOVER RC_IMAGE_HIDEANNOT_HOVER
#define RC_IMAGE_USER                   RC_PREFIX_IMAGE "user.png"
#define RC_IMAGE_USER_HOVER             RC_PREFIX_IMAGE "user_hover.png"
#define RC_IMAGE_USER_PRESSED           RC_PREFIX_IMAGE "user_pressed.png"
#define RC_IMAGE_USER_DISABLED          RC_PREFIX_IMAGE "user_disabled.png"
#define RC_IMAGE_USER_CHECKED           RC_PREFIX_IMAGE "user_checked.png"
#define RC_IMAGE_USER_CHECKED_HOVER RC_IMAGE_USER_HOVER
#define RC_IMAGE_SNAPSHOT               RC_PREFIX_IMAGE "snapshot.png"
#define RC_IMAGE_SNAPSHOT_HOVER         RC_PREFIX_IMAGE "snapshot_hover.png"
#define RC_IMAGE_SNAPSHOT_PRESSED       RC_PREFIX_IMAGE "snapshot_pressed.png"
#define RC_IMAGE_SNAPSHOT_DISABLED      RC_PREFIX_IMAGE "snapshot_disabled.png"
#define RC_IMAGE_SNAPSHOT_CHECKED       RC_PREFIX_IMAGE "snapshot_checked.png"
#define RC_IMAGE_SNAPSHOT_CHECKED_HOVER RC_IMAGE_SNAPSHOT_HOVER
#define RC_IMAGE_MENU                   RC_PREFIX_IMAGE "menu.png"
#define RC_IMAGE_MENU_HOVER             RC_PREFIX_IMAGE "menu_hover.png"
#define RC_IMAGE_MENU_PRESSED           RC_PREFIX_IMAGE "menu_pressed.png"
#define RC_IMAGE_MENU_DISABLED          RC_PREFIX_IMAGE "menu_disabled.png"
#define RC_IMAGE_MENU_CHECKED           RC_PREFIX_IMAGE "menu_checked.png"
#define RC_IMAGE_MENU_CHECKED_HOVER RC_IMAGE_MENU_HOVER

// - Buttons -

#define RC_IMAGE_DOWNARROW              RC_PREFIX_IMAGE "downarrow.png"
#define RC_IMAGE_DOWNARROW_HOVER        RC_PREFIX_IMAGE "downarrow_hover.png"
#define RC_IMAGE_DOWNARROW_PRESSED      RC_PREFIX_IMAGE "downarrow_pressed.png"
#define RC_IMAGE_DOWNARROW_DISABLED     RC_PREFIX_IMAGE "downarrow_disabled.png"
#define RC_IMAGE_DOWNARROW_CHECKED      RC_PREFIX_IMAGE "downarrow_checked.png"
#define RC_IMAGE_DOWNARROW_CHECKED_HOVER RC_IMAGE_DOWNARROW_HOVER

#define RC_IMAGE_UPARROW                RC_PREFIX_IMAGE "uparrow.png"
#define RC_IMAGE_UPARROW_HOVER          RC_PREFIX_IMAGE "uparrow_hover.png"
#define RC_IMAGE_UPARROW_PRESSED        RC_PREFIX_IMAGE "uparrow_pressed.png"
#define RC_IMAGE_UPARROW_DISABLED       RC_PREFIX_IMAGE "uparrow_disabled.png"
#define RC_IMAGE_UPARROW_CHECKED        RC_PREFIX_IMAGE "uparrow_checked.png"
#define RC_IMAGE_UPARROW_CHECKED_HOVER RC_IMAGE_UPARROW_HOVER

// - Backgrounds -
#define RC_IMAGE_LINEEDIT       RC_PREFIX_IMAGE "lineedit.png"
#define RC_IMAGE_TEXTEDIT       RC_PREFIX_IMAGE "textedit.png"
#define RC_IMAGE_BACKGROUND     RC_PREFIX_IMAGE "background.png"
#define RC_IMAGE_WINDOW         RC_IMAGE_NULL //RC_PREFIX_IMAGE "window.png"
#define RC_IMAGE_CONTEXTMENU    RC_IMAGE_NULL //RC_PREFIX_IMAGE "contextmenu.png"

// TODO
#define RC_IMAGE_SEEK           RC_IMAGE_NULL
#define RC_IMAGE_REPLAY         RC_IMAGE_NULL

#define RC_IMAGE_SUBTITLE       RC_IMAGE_NULL
#define RC_IMAGE_SHOWSUBTITLE   RC_IMAGE_SUBTITLE
#define RC_IMAGE_HIDESUBTITLE   RC_IMAGE_SUBTITLE
#define RC_IMAGE_CURRENTSUBTITLE RC_IMAGE_PLAY

#define RC_IMAGE_FORWARD        RC_IMAGE_NULL
#define RC_IMAGE_BACKWARD       RC_IMAGE_NULL
#define RC_IMAGE_FORWARD5S      RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD5S     RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD10S     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD10S    RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD30S     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD30S    RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD60S     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD60S    RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD90S     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD90S    RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD1M      RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD1M     RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD5M      RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD5M     RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD10M     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD10M    RC_IMAGE_BACKWARD

#define RC_IMAGE_LOGO   RC_IMAGE_NULL
#define RC_IMAGE_QUIT   RC_IMAGE_NULL
#define RC_IMAGE_ABOUT  RC_IMAGE_NULL
#define RC_IMAGE_HELP   RC_IMAGE_NULL

#define RC_IMAGE_LOGIN  RC_IMAGE_NULL
#define RC_IMAGE_LOGOUT RC_IMAGE_NULL

#define RC_IMAGE_COPY   RC_IMAGE_NULL
#define RC_IMAGE_PASTE  RC_IMAGE_NULL

#define RC_IMAGE_ENABLEAUTOCLEARCONSOLE         RC_IMAGE_NULL
#define RC_IMAGE_DISABLEAUTOCLEARCONSOLE        RC_IMAGE_NULL

#define RC_IMAGE_SEEKDIALOG     RC_IMAGE_NULL
#define RC_IMAGE_LOGINDIALOG    RC_IMAGE_NULL
#define RC_IMAGE_LIVEDIALOG     RC_IMAGE_NULL
#define RC_IMAGE_SYNCDIALOG     RC_IMAGE_NULL

#define RC_IMAGE_PICKDIALOG     RC_IMAGE_NULL
#define RC_IMAGE_WINDOWPICKDIALOG       RC_IMAGE_NULL
#define RC_IMAGE_PROCESSPICKDIALOG      RC_IMAGE_NULL

#define RC_IMAGE_OPENCONTEXTMENU RC_IMAGE_NULL
#define RC_IMAGE_OPENFILE       RC_IMAGE_OPEN
#define RC_IMAGE_OPENDEVICE     RC_IMAGE_NULL
#define RC_IMAGE_OPENSUBTITLE   RC_IMAGE_NULL

#define RC_IMAGE_ADVANCED       RC_IMAGE_NULL
#define RC_IMAGE_CLEARCACHE     RC_IMAGE_NULL

#define RC_IMAGE_CONNECT        RC_IMAGE_NULL
#define RC_IMAGE_DISCONNECT     RC_IMAGE_NULL

#define RC_IMAGE_WINDOWSTAYSONTOP RC_IMAGE_NULL

#define RC_IMAGE_ANNOTATIONBROWSER RC_IMAGE_NULL
#define RC_IMAGE_ANNOTATIONEDITOR RC_IMAGE_NULL
#define RC_IMAGE_TOKENVIEW      RC_IMAGE_NULL
#define RC_IMAGE_COMMENTVIEW    RC_IMAGE_NULL
#define RC_IMAGE_CLOUDVIEW      RC_IMAGE_NULL
#define RC_IMAGE_SIGNALVIEW     RC_IMAGE_NULL

#define RC_IMAGE_EDIT           RC_IMAGE_NULL
#define RC_IMAGE_HIDE           RC_IMAGE_NULL
#define RC_IMAGE_SHOW           RC_IMAGE_NULL
#define RC_IMAGE_BLOCK          RC_IMAGE_NULL
#define RC_IMAGE_BLESS          RC_IMAGE_NULL
#define RC_IMAGE_CURSE          RC_IMAGE_NULL
#define RC_IMAGE_VIEW           RC_IMAGE_NULL

#define RC_IMAGE_EDITTHISANNOT  RC_IMAGE_EDIT
#define RC_IMAGE_BLOCKTHISANNOT RC_IMAGE_BLOCK
#define RC_IMAGE_BLESSTHISANNOT RC_IMAGE_BLESS
#define RC_IMAGE_CURSETHISANNOT RC_IMAGE_CURSE
#define RC_IMAGE_HIDETHISANNOT  RC_IMAGE_HIDE
#define RC_IMAGE_SHOWTHISANNOT  RC_IMAGE_SHOW
#define RC_IMAGE_COPYTHISANNOT  RC_IMAGE_COPY

#define RC_IMAGE_VIEWTHISUSER   RC_IMAGE_VIEW
#define RC_IMAGE_BLOCKTHISUSER  RC_IMAGE_BLOCK

#define RC_IMAGE_REFRESH        RC_IMAGE_NULL
#define RC_IMAGE_REFRESHPROCESS RC_IMAGE_REFRESH
#define RC_IMAGE_ATTACHPROCESS  RC_IMAGE_NULL
#define RC_IMAGE_DETACHPROCESS  RC_IMAGE_NULL

#define RC_IMAGE_RECENTMESSAGES RC_IMAGE_NULL

#define RC_IMAGE_TRANSLATE      RC_IMAGE_NULL

#define RC_IMAGE_RECENT         RC_IMAGE_NULL
#define RC_IMAGE_RECENTFILE     RC_IMAGE_NULL
#define RC_IMAGE_CLEARRECENT    RC_IMAGE_NULL

#define RC_IMAGE_ENGLISH        RC_IMAGE_NULL
#define RC_IMAGE_JAPANESE       RC_IMAGE_NULL
#define RC_IMAGE_CHINESE        RC_IMAGE_NULL
#define RC_IMAGE_KOREAN         RC_IMAGE_NULL
#define RC_IMAGE_UKNOWN         RC_IMAGE_NULL
#define RC_IMAGE_UNKNOWNLANGUAGE RC_IMAGE_NULL
#define RC_IMAGE_ANYLANGUAGE    RC_IMAGE_NULL
#define RC_IMAGE_TRADITIONALCHINESE RC_IMAGE_NULL
#define RC_IMAGE_SIMPLIFIEDCHINESE  RC_IMAGE_NULL

#define RC_IMAGE_ANONYMOUS  RC_IMAGE_NULL

#define RC_IMAGE_SUBTITLEONTOP  RC_IMAGE_NULL

#endif // RC_H
