/* AnnotCloudServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.9 from cloudservice.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef AnnotCloudServiceSoapBindingProxy_H
#define AnnotCloudServiceSoapBindingProxy_H
#include "AnnotH.h"

namespace Annot {

class SOAP_CMAC CloudServiceSoapBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'CloudServiceSoapBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	CloudServiceSoapBindingProxy();
	/// Construct from another engine state
	CloudServiceSoapBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	CloudServiceSoapBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	CloudServiceSoapBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	CloudServiceSoapBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	CloudServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~CloudServiceSoapBindingProxy();
	/// Initializer used by constructors
	virtual	void CloudServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'blessMediaAliasWithId' (returns error code or SOAP_OK)
	virtual	int blessMediaAliasWithId(tns__blessMediaAliasWithId *tns__blessMediaAliasWithId_, tns__blessMediaAliasWithIdResponse *tns__blessMediaAliasWithIdResponse_) { return blessMediaAliasWithId(NULL, NULL, tns__blessMediaAliasWithId_, tns__blessMediaAliasWithIdResponse_); }
	virtual	int blessMediaAliasWithId(const char *endpoint, const char *soap_action, tns__blessMediaAliasWithId *tns__blessMediaAliasWithId_, tns__blessMediaAliasWithIdResponse *tns__blessMediaAliasWithIdResponse_);

	/// Web service operation 'blessMediaAnnotationWithId' (returns error code or SOAP_OK)
	virtual	int blessMediaAnnotationWithId(tns__blessMediaAnnotationWithId *tns__blessMediaAnnotationWithId_, tns__blessMediaAnnotationWithIdResponse *tns__blessMediaAnnotationWithIdResponse_) { return blessMediaAnnotationWithId(NULL, NULL, tns__blessMediaAnnotationWithId_, tns__blessMediaAnnotationWithIdResponse_); }
	virtual	int blessMediaAnnotationWithId(const char *endpoint, const char *soap_action, tns__blessMediaAnnotationWithId *tns__blessMediaAnnotationWithId_, tns__blessMediaAnnotationWithIdResponse *tns__blessMediaAnnotationWithIdResponse_);

	/// Web service operation 'blessMediaTokenWithId' (returns error code or SOAP_OK)
	virtual	int blessMediaTokenWithId(tns__blessMediaTokenWithId *tns__blessMediaTokenWithId_, tns__blessMediaTokenWithIdResponse *tns__blessMediaTokenWithIdResponse_) { return blessMediaTokenWithId(NULL, NULL, tns__blessMediaTokenWithId_, tns__blessMediaTokenWithIdResponse_); }
	virtual	int blessMediaTokenWithId(const char *endpoint, const char *soap_action, tns__blessMediaTokenWithId *tns__blessMediaTokenWithId_, tns__blessMediaTokenWithIdResponse *tns__blessMediaTokenWithIdResponse_);

	/// Web service operation 'blessUserWithId' (returns error code or SOAP_OK)
	virtual	int blessUserWithId(tns__blessUserWithId *tns__blessUserWithId_, tns__blessUserWithIdResponse *tns__blessUserWithIdResponse_) { return blessUserWithId(NULL, NULL, tns__blessUserWithId_, tns__blessUserWithIdResponse_); }
	virtual	int blessUserWithId(const char *endpoint, const char *soap_action, tns__blessUserWithId *tns__blessUserWithId_, tns__blessUserWithIdResponse *tns__blessUserWithIdResponse_);

	/// Web service operation 'blockMediaAliasWithId' (returns error code or SOAP_OK)
	virtual	int blockMediaAliasWithId(tns__blockMediaAliasWithId *tns__blockMediaAliasWithId_, tns__blockMediaAliasWithIdResponse *tns__blockMediaAliasWithIdResponse_) { return blockMediaAliasWithId(NULL, NULL, tns__blockMediaAliasWithId_, tns__blockMediaAliasWithIdResponse_); }
	virtual	int blockMediaAliasWithId(const char *endpoint, const char *soap_action, tns__blockMediaAliasWithId *tns__blockMediaAliasWithId_, tns__blockMediaAliasWithIdResponse *tns__blockMediaAliasWithIdResponse_);

	/// Web service operation 'blockMediaAnnotationWithId' (returns error code or SOAP_OK)
	virtual	int blockMediaAnnotationWithId(tns__blockMediaAnnotationWithId *tns__blockMediaAnnotationWithId_, tns__blockMediaAnnotationWithIdResponse *tns__blockMediaAnnotationWithIdResponse_) { return blockMediaAnnotationWithId(NULL, NULL, tns__blockMediaAnnotationWithId_, tns__blockMediaAnnotationWithIdResponse_); }
	virtual	int blockMediaAnnotationWithId(const char *endpoint, const char *soap_action, tns__blockMediaAnnotationWithId *tns__blockMediaAnnotationWithId_, tns__blockMediaAnnotationWithIdResponse *tns__blockMediaAnnotationWithIdResponse_);

	/// Web service operation 'blockUserWithId' (returns error code or SOAP_OK)
	virtual	int blockUserWithId(tns__blockUserWithId *tns__blockUserWithId_, tns__blockUserWithIdResponse *tns__blockUserWithIdResponse_) { return blockUserWithId(NULL, NULL, tns__blockUserWithId_, tns__blockUserWithIdResponse_); }
	virtual	int blockUserWithId(const char *endpoint, const char *soap_action, tns__blockUserWithId *tns__blockUserWithId_, tns__blockUserWithIdResponse *tns__blockUserWithIdResponse_);

	/// Web service operation 'chat' (returns error code or SOAP_OK)
	virtual	int chat(tns__chat *tns__chat_, tns__chatResponse *tns__chatResponse_) { return chat(NULL, NULL, tns__chat_, tns__chatResponse_); }
	virtual	int chat(const char *endpoint, const char *soap_action, tns__chat *tns__chat_, tns__chatResponse *tns__chatResponse_);

	/// Web service operation 'curseMediaAliasWithId' (returns error code or SOAP_OK)
	virtual	int curseMediaAliasWithId(tns__curseMediaAliasWithId *tns__curseMediaAliasWithId_, tns__curseMediaAliasWithIdResponse *tns__curseMediaAliasWithIdResponse_) { return curseMediaAliasWithId(NULL, NULL, tns__curseMediaAliasWithId_, tns__curseMediaAliasWithIdResponse_); }
	virtual	int curseMediaAliasWithId(const char *endpoint, const char *soap_action, tns__curseMediaAliasWithId *tns__curseMediaAliasWithId_, tns__curseMediaAliasWithIdResponse *tns__curseMediaAliasWithIdResponse_);

	/// Web service operation 'curseMediaAnnotationWithId' (returns error code or SOAP_OK)
	virtual	int curseMediaAnnotationWithId(tns__curseMediaAnnotationWithId *tns__curseMediaAnnotationWithId_, tns__curseMediaAnnotationWithIdResponse *tns__curseMediaAnnotationWithIdResponse_) { return curseMediaAnnotationWithId(NULL, NULL, tns__curseMediaAnnotationWithId_, tns__curseMediaAnnotationWithIdResponse_); }
	virtual	int curseMediaAnnotationWithId(const char *endpoint, const char *soap_action, tns__curseMediaAnnotationWithId *tns__curseMediaAnnotationWithId_, tns__curseMediaAnnotationWithIdResponse *tns__curseMediaAnnotationWithIdResponse_);

	/// Web service operation 'curseMediaTokenWithId' (returns error code or SOAP_OK)
	virtual	int curseMediaTokenWithId(tns__curseMediaTokenWithId *tns__curseMediaTokenWithId_, tns__curseMediaTokenWithIdResponse *tns__curseMediaTokenWithIdResponse_) { return curseMediaTokenWithId(NULL, NULL, tns__curseMediaTokenWithId_, tns__curseMediaTokenWithIdResponse_); }
	virtual	int curseMediaTokenWithId(const char *endpoint, const char *soap_action, tns__curseMediaTokenWithId *tns__curseMediaTokenWithId_, tns__curseMediaTokenWithIdResponse *tns__curseMediaTokenWithIdResponse_);

	/// Web service operation 'curseUserWithId' (returns error code or SOAP_OK)
	virtual	int curseUserWithId(tns__curseUserWithId *tns__curseUserWithId_, tns__curseUserWithIdResponse *tns__curseUserWithIdResponse_) { return curseUserWithId(NULL, NULL, tns__curseUserWithId_, tns__curseUserWithIdResponse_); }
	virtual	int curseUserWithId(const char *endpoint, const char *soap_action, tns__curseUserWithId *tns__curseUserWithId_, tns__curseUserWithIdResponse *tns__curseUserWithIdResponse_);

	/// Web service operation 'deleteMediaAliasWithId' (returns error code or SOAP_OK)
	virtual	int deleteMediaAliasWithId(tns__deleteMediaAliasWithId *tns__deleteMediaAliasWithId_, tns__deleteMediaAliasWithIdResponse *tns__deleteMediaAliasWithIdResponse_) { return deleteMediaAliasWithId(NULL, NULL, tns__deleteMediaAliasWithId_, tns__deleteMediaAliasWithIdResponse_); }
	virtual	int deleteMediaAliasWithId(const char *endpoint, const char *soap_action, tns__deleteMediaAliasWithId *tns__deleteMediaAliasWithId_, tns__deleteMediaAliasWithIdResponse *tns__deleteMediaAliasWithIdResponse_);

	/// Web service operation 'deleteMediaAnnotationWithId' (returns error code or SOAP_OK)
	virtual	int deleteMediaAnnotationWithId(tns__deleteMediaAnnotationWithId *tns__deleteMediaAnnotationWithId_, tns__deleteMediaAnnotationWithIdResponse *tns__deleteMediaAnnotationWithIdResponse_) { return deleteMediaAnnotationWithId(NULL, NULL, tns__deleteMediaAnnotationWithId_, tns__deleteMediaAnnotationWithIdResponse_); }
	virtual	int deleteMediaAnnotationWithId(const char *endpoint, const char *soap_action, tns__deleteMediaAnnotationWithId *tns__deleteMediaAnnotationWithId_, tns__deleteMediaAnnotationWithIdResponse *tns__deleteMediaAnnotationWithIdResponse_);

	/// Web service operation 'getUser' (returns error code or SOAP_OK)
	virtual	int getUser(tns__getUser *tns__getUser_, tns__getUserResponse *tns__getUserResponse_) { return getUser(NULL, NULL, tns__getUser_, tns__getUserResponse_); }
	virtual	int getUser(const char *endpoint, const char *soap_action, tns__getUser *tns__getUser_, tns__getUserResponse *tns__getUserResponse_);

	/// Web service operation 'isAuthorized' (returns error code or SOAP_OK)
	virtual	int isAuthorized(tns__isAuthorized *tns__isAuthorized_, tns__isAuthorizedResponse *tns__isAuthorizedResponse_) { return isAuthorized(NULL, NULL, tns__isAuthorized_, tns__isAuthorizedResponse_); }
	virtual	int isAuthorized(const char *endpoint, const char *soap_action, tns__isAuthorized *tns__isAuthorized_, tns__isAuthorizedResponse *tns__isAuthorizedResponse_);

	/// Web service operation 'isConnected' (returns error code or SOAP_OK)
	virtual	int isConnected(tns__isConnected *tns__isConnected_, tns__isConnectedResponse *tns__isConnectedResponse_) { return isConnected(NULL, NULL, tns__isConnected_, tns__isConnectedResponse_); }
	virtual	int isConnected(const char *endpoint, const char *soap_action, tns__isConnected *tns__isConnected_, tns__isConnectedResponse *tns__isConnectedResponse_);

	/// Web service operation 'isLatestApp' (returns error code or SOAP_OK)
	virtual	int isLatestApp(tns__isLatestApp *tns__isLatestApp_, tns__isLatestAppResponse *tns__isLatestAppResponse_) { return isLatestApp(NULL, NULL, tns__isLatestApp_, tns__isLatestAppResponse_); }
	virtual	int isLatestApp(const char *endpoint, const char *soap_action, tns__isLatestApp *tns__isLatestApp_, tns__isLatestAppResponse *tns__isLatestAppResponse_);

	/// Web service operation 'login' (returns error code or SOAP_OK)
	virtual	int login(tns__login *tns__login_, tns__loginResponse *tns__loginResponse_) { return login(NULL, NULL, tns__login_, tns__loginResponse_); }
	virtual	int login(const char *endpoint, const char *soap_action, tns__login *tns__login_, tns__loginResponse *tns__loginResponse_);

	/// Web service operation 'selectMediaAliasesWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectMediaAliasesWithTokenId(tns__selectMediaAliasesWithTokenId *tns__selectMediaAliasesWithTokenId_, tns__selectMediaAliasesWithTokenIdResponse *tns__selectMediaAliasesWithTokenIdResponse_) { return selectMediaAliasesWithTokenId(NULL, NULL, tns__selectMediaAliasesWithTokenId_, tns__selectMediaAliasesWithTokenIdResponse_); }
	virtual	int selectMediaAliasesWithTokenId(const char *endpoint, const char *soap_action, tns__selectMediaAliasesWithTokenId *tns__selectMediaAliasesWithTokenId_, tns__selectMediaAliasesWithTokenIdResponse *tns__selectMediaAliasesWithTokenIdResponse_);

	/// Web service operation 'selectMediaAnnotationsWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectMediaAnnotationsWithTokenId(tns__selectMediaAnnotationsWithTokenId *tns__selectMediaAnnotationsWithTokenId_, tns__selectMediaAnnotationsWithTokenIdResponse *tns__selectMediaAnnotationsWithTokenIdResponse_) { return selectMediaAnnotationsWithTokenId(NULL, NULL, tns__selectMediaAnnotationsWithTokenId_, tns__selectMediaAnnotationsWithTokenIdResponse_); }
	virtual	int selectMediaAnnotationsWithTokenId(const char *endpoint, const char *soap_action, tns__selectMediaAnnotationsWithTokenId *tns__selectMediaAnnotationsWithTokenId_, tns__selectMediaAnnotationsWithTokenIdResponse *tns__selectMediaAnnotationsWithTokenIdResponse_);

	/// Web service operation 'selectMediaTokenIdWithDigest' (returns error code or SOAP_OK)
	virtual	int selectMediaTokenIdWithDigest(tns__selectMediaTokenIdWithDigest *tns__selectMediaTokenIdWithDigest_, tns__selectMediaTokenIdWithDigestResponse *tns__selectMediaTokenIdWithDigestResponse_) { return selectMediaTokenIdWithDigest(NULL, NULL, tns__selectMediaTokenIdWithDigest_, tns__selectMediaTokenIdWithDigestResponse_); }
	virtual	int selectMediaTokenIdWithDigest(const char *endpoint, const char *soap_action, tns__selectMediaTokenIdWithDigest *tns__selectMediaTokenIdWithDigest_, tns__selectMediaTokenIdWithDigestResponse *tns__selectMediaTokenIdWithDigestResponse_);

	/// Web service operation 'selectMediaTokenIdWithUrl' (returns error code or SOAP_OK)
	virtual	int selectMediaTokenIdWithUrl(tns__selectMediaTokenIdWithUrl *tns__selectMediaTokenIdWithUrl_, tns__selectMediaTokenIdWithUrlResponse *tns__selectMediaTokenIdWithUrlResponse_) { return selectMediaTokenIdWithUrl(NULL, NULL, tns__selectMediaTokenIdWithUrl_, tns__selectMediaTokenIdWithUrlResponse_); }
	virtual	int selectMediaTokenIdWithUrl(const char *endpoint, const char *soap_action, tns__selectMediaTokenIdWithUrl *tns__selectMediaTokenIdWithUrl_, tns__selectMediaTokenIdWithUrlResponse *tns__selectMediaTokenIdWithUrlResponse_);

	/// Web service operation 'selectMediaTokenWithDigest' (returns error code or SOAP_OK)
	virtual	int selectMediaTokenWithDigest(tns__selectMediaTokenWithDigest *tns__selectMediaTokenWithDigest_, tns__selectMediaTokenWithDigestResponse *tns__selectMediaTokenWithDigestResponse_) { return selectMediaTokenWithDigest(NULL, NULL, tns__selectMediaTokenWithDigest_, tns__selectMediaTokenWithDigestResponse_); }
	virtual	int selectMediaTokenWithDigest(const char *endpoint, const char *soap_action, tns__selectMediaTokenWithDigest *tns__selectMediaTokenWithDigest_, tns__selectMediaTokenWithDigestResponse *tns__selectMediaTokenWithDigestResponse_);

	/// Web service operation 'selectMediaTokenWithId' (returns error code or SOAP_OK)
	virtual	int selectMediaTokenWithId(tns__selectMediaTokenWithId *tns__selectMediaTokenWithId_, tns__selectMediaTokenWithIdResponse *tns__selectMediaTokenWithIdResponse_) { return selectMediaTokenWithId(NULL, NULL, tns__selectMediaTokenWithId_, tns__selectMediaTokenWithIdResponse_); }
	virtual	int selectMediaTokenWithId(const char *endpoint, const char *soap_action, tns__selectMediaTokenWithId *tns__selectMediaTokenWithId_, tns__selectMediaTokenWithIdResponse *tns__selectMediaTokenWithIdResponse_);

	/// Web service operation 'selectRelatedMediaAliasesWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectRelatedMediaAliasesWithTokenId(tns__selectRelatedMediaAliasesWithTokenId *tns__selectRelatedMediaAliasesWithTokenId_, tns__selectRelatedMediaAliasesWithTokenIdResponse *tns__selectRelatedMediaAliasesWithTokenIdResponse_) { return selectRelatedMediaAliasesWithTokenId(NULL, NULL, tns__selectRelatedMediaAliasesWithTokenId_, tns__selectRelatedMediaAliasesWithTokenIdResponse_); }
	virtual	int selectRelatedMediaAliasesWithTokenId(const char *endpoint, const char *soap_action, tns__selectRelatedMediaAliasesWithTokenId *tns__selectRelatedMediaAliasesWithTokenId_, tns__selectRelatedMediaAliasesWithTokenIdResponse *tns__selectRelatedMediaAliasesWithTokenIdResponse_);

	/// Web service operation 'selectRelatedMediaAnnotationsWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectRelatedMediaAnnotationsWithTokenId(tns__selectRelatedMediaAnnotationsWithTokenId *tns__selectRelatedMediaAnnotationsWithTokenId_, tns__selectRelatedMediaAnnotationsWithTokenIdResponse *tns__selectRelatedMediaAnnotationsWithTokenIdResponse_) { return selectRelatedMediaAnnotationsWithTokenId(NULL, NULL, tns__selectRelatedMediaAnnotationsWithTokenId_, tns__selectRelatedMediaAnnotationsWithTokenIdResponse_); }
	virtual	int selectRelatedMediaAnnotationsWithTokenId(const char *endpoint, const char *soap_action, tns__selectRelatedMediaAnnotationsWithTokenId *tns__selectRelatedMediaAnnotationsWithTokenId_, tns__selectRelatedMediaAnnotationsWithTokenIdResponse *tns__selectRelatedMediaAnnotationsWithTokenIdResponse_);

	/// Web service operation 'setUserAnonymous' (returns error code or SOAP_OK)
	virtual	int setUserAnonymous(tns__setUserAnonymous *tns__setUserAnonymous_, tns__setUserAnonymousResponse *tns__setUserAnonymousResponse_) { return setUserAnonymous(NULL, NULL, tns__setUserAnonymous_, tns__setUserAnonymousResponse_); }
	virtual	int setUserAnonymous(const char *endpoint, const char *soap_action, tns__setUserAnonymous *tns__setUserAnonymous_, tns__setUserAnonymousResponse *tns__setUserAnonymousResponse_);

	/// Web service operation 'setUserLanguage' (returns error code or SOAP_OK)
	virtual	int setUserLanguage(tns__setUserLanguage *tns__setUserLanguage_, tns__setUserLanguageResponse *tns__setUserLanguageResponse_) { return setUserLanguage(NULL, NULL, tns__setUserLanguage_, tns__setUserLanguageResponse_); }
	virtual	int setUserLanguage(const char *endpoint, const char *soap_action, tns__setUserLanguage *tns__setUserLanguage_, tns__setUserLanguageResponse *tns__setUserLanguageResponse_);

	/// Web service operation 'submitMediaAlias' (returns error code or SOAP_OK)
	virtual	int submitMediaAlias(tns__submitMediaAlias *tns__submitMediaAlias_, tns__submitMediaAliasResponse *tns__submitMediaAliasResponse_) { return submitMediaAlias(NULL, NULL, tns__submitMediaAlias_, tns__submitMediaAliasResponse_); }
	virtual	int submitMediaAlias(const char *endpoint, const char *soap_action, tns__submitMediaAlias *tns__submitMediaAlias_, tns__submitMediaAliasResponse *tns__submitMediaAliasResponse_);

	/// Web service operation 'submitMediaAliasTextAndTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitMediaAliasTextAndTokenDigest(tns__submitMediaAliasTextAndTokenDigest *tns__submitMediaAliasTextAndTokenDigest_, tns__submitMediaAliasTextAndTokenDigestResponse *tns__submitMediaAliasTextAndTokenDigestResponse_) { return submitMediaAliasTextAndTokenDigest(NULL, NULL, tns__submitMediaAliasTextAndTokenDigest_, tns__submitMediaAliasTextAndTokenDigestResponse_); }
	virtual	int submitMediaAliasTextAndTokenDigest(const char *endpoint, const char *soap_action, tns__submitMediaAliasTextAndTokenDigest *tns__submitMediaAliasTextAndTokenDigest_, tns__submitMediaAliasTextAndTokenDigestResponse *tns__submitMediaAliasTextAndTokenDigestResponse_);

	/// Web service operation 'submitMediaAliasTextWithTokenId' (returns error code or SOAP_OK)
	virtual	int submitMediaAliasTextWithTokenId(tns__submitMediaAliasTextWithTokenId *tns__submitMediaAliasTextWithTokenId_, tns__submitMediaAliasTextWithTokenIdResponse *tns__submitMediaAliasTextWithTokenIdResponse_) { return submitMediaAliasTextWithTokenId(NULL, NULL, tns__submitMediaAliasTextWithTokenId_, tns__submitMediaAliasTextWithTokenIdResponse_); }
	virtual	int submitMediaAliasTextWithTokenId(const char *endpoint, const char *soap_action, tns__submitMediaAliasTextWithTokenId *tns__submitMediaAliasTextWithTokenId_, tns__submitMediaAliasTextWithTokenIdResponse *tns__submitMediaAliasTextWithTokenIdResponse_);

	/// Web service operation 'submitMediaAnnotation' (returns error code or SOAP_OK)
	virtual	int submitMediaAnnotation(tns__submitMediaAnnotation *tns__submitMediaAnnotation_, tns__submitMediaAnnotationResponse *tns__submitMediaAnnotationResponse_) { return submitMediaAnnotation(NULL, NULL, tns__submitMediaAnnotation_, tns__submitMediaAnnotationResponse_); }
	virtual	int submitMediaAnnotation(const char *endpoint, const char *soap_action, tns__submitMediaAnnotation *tns__submitMediaAnnotation_, tns__submitMediaAnnotationResponse *tns__submitMediaAnnotationResponse_);

	/// Web service operation 'submitMediaAnnotationTextAndTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitMediaAnnotationTextAndTokenDigest(tns__submitMediaAnnotationTextAndTokenDigest *tns__submitMediaAnnotationTextAndTokenDigest_, tns__submitMediaAnnotationTextAndTokenDigestResponse *tns__submitMediaAnnotationTextAndTokenDigestResponse_) { return submitMediaAnnotationTextAndTokenDigest(NULL, NULL, tns__submitMediaAnnotationTextAndTokenDigest_, tns__submitMediaAnnotationTextAndTokenDigestResponse_); }
	virtual	int submitMediaAnnotationTextAndTokenDigest(const char *endpoint, const char *soap_action, tns__submitMediaAnnotationTextAndTokenDigest *tns__submitMediaAnnotationTextAndTokenDigest_, tns__submitMediaAnnotationTextAndTokenDigestResponse *tns__submitMediaAnnotationTextAndTokenDigestResponse_);

	/// Web service operation 'submitMediaAnnotationTextWithTokenId' (returns error code or SOAP_OK)
	virtual	int submitMediaAnnotationTextWithTokenId(tns__submitMediaAnnotationTextWithTokenId *tns__submitMediaAnnotationTextWithTokenId_, tns__submitMediaAnnotationTextWithTokenIdResponse *tns__submitMediaAnnotationTextWithTokenIdResponse_) { return submitMediaAnnotationTextWithTokenId(NULL, NULL, tns__submitMediaAnnotationTextWithTokenId_, tns__submitMediaAnnotationTextWithTokenIdResponse_); }
	virtual	int submitMediaAnnotationTextWithTokenId(const char *endpoint, const char *soap_action, tns__submitMediaAnnotationTextWithTokenId *tns__submitMediaAnnotationTextWithTokenId_, tns__submitMediaAnnotationTextWithTokenIdResponse *tns__submitMediaAnnotationTextWithTokenIdResponse_);

	/// Web service operation 'submitMediaToken' (returns error code or SOAP_OK)
	virtual	int submitMediaToken(tns__submitMediaToken *tns__submitMediaToken_, tns__submitMediaTokenResponse *tns__submitMediaTokenResponse_) { return submitMediaToken(NULL, NULL, tns__submitMediaToken_, tns__submitMediaTokenResponse_); }
	virtual	int submitMediaToken(const char *endpoint, const char *soap_action, tns__submitMediaToken *tns__submitMediaToken_, tns__submitMediaTokenResponse *tns__submitMediaTokenResponse_);

	/// Web service operation 'submitMediaTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitMediaTokenDigest(tns__submitMediaTokenDigest *tns__submitMediaTokenDigest_, tns__submitMediaTokenDigestResponse *tns__submitMediaTokenDigestResponse_) { return submitMediaTokenDigest(NULL, NULL, tns__submitMediaTokenDigest_, tns__submitMediaTokenDigestResponse_); }
	virtual	int submitMediaTokenDigest(const char *endpoint, const char *soap_action, tns__submitMediaTokenDigest *tns__submitMediaTokenDigest_, tns__submitMediaTokenDigestResponse *tns__submitMediaTokenDigestResponse_);

	/// Web service operation 'submitMediaTokenUrl' (returns error code or SOAP_OK)
	virtual	int submitMediaTokenUrl(tns__submitMediaTokenUrl *tns__submitMediaTokenUrl_, tns__submitMediaTokenUrlResponse *tns__submitMediaTokenUrlResponse_) { return submitMediaTokenUrl(NULL, NULL, tns__submitMediaTokenUrl_, tns__submitMediaTokenUrlResponse_); }
	virtual	int submitMediaTokenUrl(const char *endpoint, const char *soap_action, tns__submitMediaTokenUrl *tns__submitMediaTokenUrl_, tns__submitMediaTokenUrlResponse *tns__submitMediaTokenUrlResponse_);

	/// Web service operation 'updateMediaAnnotationTextWithId' (returns error code or SOAP_OK)
	virtual	int updateMediaAnnotationTextWithId(tns__updateMediaAnnotationTextWithId *tns__updateMediaAnnotationTextWithId_, tns__updateMediaAnnotationTextWithIdResponse *tns__updateMediaAnnotationTextWithIdResponse_) { return updateMediaAnnotationTextWithId(NULL, NULL, tns__updateMediaAnnotationTextWithId_, tns__updateMediaAnnotationTextWithIdResponse_); }
	virtual	int updateMediaAnnotationTextWithId(const char *endpoint, const char *soap_action, tns__updateMediaAnnotationTextWithId *tns__updateMediaAnnotationTextWithId_, tns__updateMediaAnnotationTextWithIdResponse *tns__updateMediaAnnotationTextWithIdResponse_);

	/// Web service operation 'updateMediaAnnotationUserIdWithId' (returns error code or SOAP_OK)
	virtual	int updateMediaAnnotationUserIdWithId(tns__updateMediaAnnotationUserIdWithId *tns__updateMediaAnnotationUserIdWithId_, tns__updateMediaAnnotationUserIdWithIdResponse *tns__updateMediaAnnotationUserIdWithIdResponse_) { return updateMediaAnnotationUserIdWithId(NULL, NULL, tns__updateMediaAnnotationUserIdWithId_, tns__updateMediaAnnotationUserIdWithIdResponse_); }
	virtual	int updateMediaAnnotationUserIdWithId(const char *endpoint, const char *soap_action, tns__updateMediaAnnotationUserIdWithId *tns__updateMediaAnnotationUserIdWithId_, tns__updateMediaAnnotationUserIdWithIdResponse *tns__updateMediaAnnotationUserIdWithIdResponse_);
};

} // namespace Annot

#endif
