#!/bin/sh
# check an app is installed and launch it in the background

type $1 > /dev/null 2>&1 
if [ $? = 1 ]; then 
echo $1 'is not installed' 
else 
nohup $@ > /dev/null 2>&1 &
fi         
            

