/* ClientSoapClientAgentServiceSoapBindingService.h
   Generated by gSOAP 2.8.3 from _clientsoap.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef ClientSoapClientAgentServiceSoapBindingService_H
#define ClientSoapClientAgentServiceSoapBindingService_H
#include "ClientSoapH.h"

namespace ClientSoap {
class SOAP_CMAC ClientAgentServiceSoapBindingService : public soap
{ public:
	/// Constructor
	ClientAgentServiceSoapBindingService();
	/// Constructor with copy of another engine state
	ClientAgentServiceSoapBindingService(const struct soap&);
	/// Constructor with engine input+output mode control
	ClientAgentServiceSoapBindingService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	ClientAgentServiceSoapBindingService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~ClientAgentServiceSoapBindingService();
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Initializer used by constructor
	virtual	void ClientAgentServiceSoapBindingService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	ClientAgentServiceSoapBindingService *copy() SOAP_PURE_VIRTUAL;
	/// Force close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	/// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
	///

	/// Web service operation 'authorize' (returns error code or SOAP_OK)
	virtual	int authorize(tns__authorize *tns__authorize_, tns__authorizeResponse *tns__authorizeResponse_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'deauthorize' (returns error code or SOAP_OK)
	virtual	int deauthorize(tns__deauthorize *tns__deauthorize_, tns__deauthorizeResponse *tns__deauthorizeResponse_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'isAuthorized' (returns error code or SOAP_OK)
	virtual	int isAuthorized(tns__isAuthorized *tns__isAuthorized_, tns__isAuthorizedResponse *tns__isAuthorizedResponse_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'isConnected' (returns error code or SOAP_OK)
	virtual	int isConnected(tns__isConnected *tns__isConnected_, tns__isConnectedResponse *tns__isConnectedResponse_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'chat' (returns error code or SOAP_OK)
	virtual	int chat(tns__chat *tns__chat_, tns__chatResponse *tns__chatResponse_) SOAP_PURE_VIRTUAL;
};

} // namespace ClientSoap

#endif
