/* ServerSoapServerAgentServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.5 from _serversoap.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef ServerSoapServerAgentServiceSoapBindingProxy_H
#define ServerSoapServerAgentServiceSoapBindingProxy_H
#include "ServerSoapH.h"

namespace ServerSoap {

class SOAP_CMAC ServerAgentServiceSoapBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'ServerAgentServiceSoapBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ServerAgentServiceSoapBindingProxy();
	/// Constructor with copy of another engine state
	ServerAgentServiceSoapBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	ServerAgentServiceSoapBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	ServerAgentServiceSoapBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ServerAgentServiceSoapBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ServerAgentServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ServerAgentServiceSoapBindingProxy();
	/// Initializer used by constructors
	virtual	void ServerAgentServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'blessMediaAliasWithId' (returns error code or SOAP_OK)
	virtual	int blessMediaAliasWithId(tns__blessMediaAliasWithId *tns__blessMediaAliasWithId_, tns__blessMediaAliasWithIdResponse *tns__blessMediaAliasWithIdResponse_) { return blessMediaAliasWithId(NULL, NULL, tns__blessMediaAliasWithId_, tns__blessMediaAliasWithIdResponse_); }
	virtual	int blessMediaAliasWithId(const char *endpoint, const char *soap_action, tns__blessMediaAliasWithId *tns__blessMediaAliasWithId_, tns__blessMediaAliasWithIdResponse *tns__blessMediaAliasWithIdResponse_);

	/// Web service operation 'blessMediaAnnotationWithId' (returns error code or SOAP_OK)
	virtual	int blessMediaAnnotationWithId(tns__blessMediaAnnotationWithId *tns__blessMediaAnnotationWithId_, tns__blessMediaAnnotationWithIdResponse *tns__blessMediaAnnotationWithIdResponse_) { return blessMediaAnnotationWithId(NULL, NULL, tns__blessMediaAnnotationWithId_, tns__blessMediaAnnotationWithIdResponse_); }
	virtual	int blessMediaAnnotationWithId(const char *endpoint, const char *soap_action, tns__blessMediaAnnotationWithId *tns__blessMediaAnnotationWithId_, tns__blessMediaAnnotationWithIdResponse *tns__blessMediaAnnotationWithIdResponse_);

	/// Web service operation 'blessMediaTokenWithId' (returns error code or SOAP_OK)
	virtual	int blessMediaTokenWithId(tns__blessMediaTokenWithId *tns__blessMediaTokenWithId_, tns__blessMediaTokenWithIdResponse *tns__blessMediaTokenWithIdResponse_) { return blessMediaTokenWithId(NULL, NULL, tns__blessMediaTokenWithId_, tns__blessMediaTokenWithIdResponse_); }
	virtual	int blessMediaTokenWithId(const char *endpoint, const char *soap_action, tns__blessMediaTokenWithId *tns__blessMediaTokenWithId_, tns__blessMediaTokenWithIdResponse *tns__blessMediaTokenWithIdResponse_);

	/// Web service operation 'blockMediaAliasWithId' (returns error code or SOAP_OK)
	virtual	int blockMediaAliasWithId(tns__blockMediaAliasWithId *tns__blockMediaAliasWithId_, tns__blockMediaAliasWithIdResponse *tns__blockMediaAliasWithIdResponse_) { return blockMediaAliasWithId(NULL, NULL, tns__blockMediaAliasWithId_, tns__blockMediaAliasWithIdResponse_); }
	virtual	int blockMediaAliasWithId(const char *endpoint, const char *soap_action, tns__blockMediaAliasWithId *tns__blockMediaAliasWithId_, tns__blockMediaAliasWithIdResponse *tns__blockMediaAliasWithIdResponse_);

	/// Web service operation 'blockMediaAnnotationWithId' (returns error code or SOAP_OK)
	virtual	int blockMediaAnnotationWithId(tns__blockMediaAnnotationWithId *tns__blockMediaAnnotationWithId_, tns__blockMediaAnnotationWithIdResponse *tns__blockMediaAnnotationWithIdResponse_) { return blockMediaAnnotationWithId(NULL, NULL, tns__blockMediaAnnotationWithId_, tns__blockMediaAnnotationWithIdResponse_); }
	virtual	int blockMediaAnnotationWithId(const char *endpoint, const char *soap_action, tns__blockMediaAnnotationWithId *tns__blockMediaAnnotationWithId_, tns__blockMediaAnnotationWithIdResponse *tns__blockMediaAnnotationWithIdResponse_);

	/// Web service operation 'blockUserWithId' (returns error code or SOAP_OK)
	virtual	int blockUserWithId(tns__blockUserWithId *tns__blockUserWithId_, tns__blockUserWithIdResponse *tns__blockUserWithIdResponse_) { return blockUserWithId(NULL, NULL, tns__blockUserWithId_, tns__blockUserWithIdResponse_); }
	virtual	int blockUserWithId(const char *endpoint, const char *soap_action, tns__blockUserWithId *tns__blockUserWithId_, tns__blockUserWithIdResponse *tns__blockUserWithIdResponse_);

	/// Web service operation 'chat' (returns error code or SOAP_OK)
	virtual	int chat(tns__chat *tns__chat_, tns__chatResponse *tns__chatResponse_) { return chat(NULL, NULL, tns__chat_, tns__chatResponse_); }
	virtual	int chat(const char *endpoint, const char *soap_action, tns__chat *tns__chat_, tns__chatResponse *tns__chatResponse_);

	/// Web service operation 'curseMediaAliasWithId' (returns error code or SOAP_OK)
	virtual	int curseMediaAliasWithId(tns__curseMediaAliasWithId *tns__curseMediaAliasWithId_, tns__curseMediaAliasWithIdResponse *tns__curseMediaAliasWithIdResponse_) { return curseMediaAliasWithId(NULL, NULL, tns__curseMediaAliasWithId_, tns__curseMediaAliasWithIdResponse_); }
	virtual	int curseMediaAliasWithId(const char *endpoint, const char *soap_action, tns__curseMediaAliasWithId *tns__curseMediaAliasWithId_, tns__curseMediaAliasWithIdResponse *tns__curseMediaAliasWithIdResponse_);

	/// Web service operation 'curseMediaAnnotationWithId' (returns error code or SOAP_OK)
	virtual	int curseMediaAnnotationWithId(tns__curseMediaAnnotationWithId *tns__curseMediaAnnotationWithId_, tns__curseMediaAnnotationWithIdResponse *tns__curseMediaAnnotationWithIdResponse_) { return curseMediaAnnotationWithId(NULL, NULL, tns__curseMediaAnnotationWithId_, tns__curseMediaAnnotationWithIdResponse_); }
	virtual	int curseMediaAnnotationWithId(const char *endpoint, const char *soap_action, tns__curseMediaAnnotationWithId *tns__curseMediaAnnotationWithId_, tns__curseMediaAnnotationWithIdResponse *tns__curseMediaAnnotationWithIdResponse_);

	/// Web service operation 'curseMediaTokenWithId' (returns error code or SOAP_OK)
	virtual	int curseMediaTokenWithId(tns__curseMediaTokenWithId *tns__curseMediaTokenWithId_, tns__curseMediaTokenWithIdResponse *tns__curseMediaTokenWithIdResponse_) { return curseMediaTokenWithId(NULL, NULL, tns__curseMediaTokenWithId_, tns__curseMediaTokenWithIdResponse_); }
	virtual	int curseMediaTokenWithId(const char *endpoint, const char *soap_action, tns__curseMediaTokenWithId *tns__curseMediaTokenWithId_, tns__curseMediaTokenWithIdResponse *tns__curseMediaTokenWithIdResponse_);

	/// Web service operation 'isClientUpdated' (returns error code or SOAP_OK)
	virtual	int isClientUpdated(tns__isClientUpdated *tns__isClientUpdated_, tns__isClientUpdatedResponse *tns__isClientUpdatedResponse_) { return isClientUpdated(NULL, NULL, tns__isClientUpdated_, tns__isClientUpdatedResponse_); }
	virtual	int isClientUpdated(const char *endpoint, const char *soap_action, tns__isClientUpdated *tns__isClientUpdated_, tns__isClientUpdatedResponse *tns__isClientUpdatedResponse_);

	/// Web service operation 'isConnected' (returns error code or SOAP_OK)
	virtual	int isConnected(tns__isConnected *tns__isConnected_, tns__isConnectedResponse *tns__isConnectedResponse_) { return isConnected(NULL, NULL, tns__isConnected_, tns__isConnectedResponse_); }
	virtual	int isConnected(const char *endpoint, const char *soap_action, tns__isConnected *tns__isConnected_, tns__isConnectedResponse *tns__isConnectedResponse_);

	/// Web service operation 'selectMediaAliasesWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectMediaAliasesWithTokenId(tns__selectMediaAliasesWithTokenId *tns__selectMediaAliasesWithTokenId_, tns__selectMediaAliasesWithTokenIdResponse *tns__selectMediaAliasesWithTokenIdResponse_) { return selectMediaAliasesWithTokenId(NULL, NULL, tns__selectMediaAliasesWithTokenId_, tns__selectMediaAliasesWithTokenIdResponse_); }
	virtual	int selectMediaAliasesWithTokenId(const char *endpoint, const char *soap_action, tns__selectMediaAliasesWithTokenId *tns__selectMediaAliasesWithTokenId_, tns__selectMediaAliasesWithTokenIdResponse *tns__selectMediaAliasesWithTokenIdResponse_);

	/// Web service operation 'selectMediaAnnotationsWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectMediaAnnotationsWithTokenId(tns__selectMediaAnnotationsWithTokenId *tns__selectMediaAnnotationsWithTokenId_, tns__selectMediaAnnotationsWithTokenIdResponse *tns__selectMediaAnnotationsWithTokenIdResponse_) { return selectMediaAnnotationsWithTokenId(NULL, NULL, tns__selectMediaAnnotationsWithTokenId_, tns__selectMediaAnnotationsWithTokenIdResponse_); }
	virtual	int selectMediaAnnotationsWithTokenId(const char *endpoint, const char *soap_action, tns__selectMediaAnnotationsWithTokenId *tns__selectMediaAnnotationsWithTokenId_, tns__selectMediaAnnotationsWithTokenIdResponse *tns__selectMediaAnnotationsWithTokenIdResponse_);

	/// Web service operation 'selectMediaTokenWithDigest' (returns error code or SOAP_OK)
	virtual	int selectMediaTokenWithDigest(tns__selectMediaTokenWithDigest *tns__selectMediaTokenWithDigest_, tns__selectMediaTokenWithDigestResponse *tns__selectMediaTokenWithDigestResponse_) { return selectMediaTokenWithDigest(NULL, NULL, tns__selectMediaTokenWithDigest_, tns__selectMediaTokenWithDigestResponse_); }
	virtual	int selectMediaTokenWithDigest(const char *endpoint, const char *soap_action, tns__selectMediaTokenWithDigest *tns__selectMediaTokenWithDigest_, tns__selectMediaTokenWithDigestResponse *tns__selectMediaTokenWithDigestResponse_);

	/// Web service operation 'selectMediaTokenWithId' (returns error code or SOAP_OK)
	virtual	int selectMediaTokenWithId(tns__selectMediaTokenWithId *tns__selectMediaTokenWithId_, tns__selectMediaTokenWithIdResponse *tns__selectMediaTokenWithIdResponse_) { return selectMediaTokenWithId(NULL, NULL, tns__selectMediaTokenWithId_, tns__selectMediaTokenWithIdResponse_); }
	virtual	int selectMediaTokenWithId(const char *endpoint, const char *soap_action, tns__selectMediaTokenWithId *tns__selectMediaTokenWithId_, tns__selectMediaTokenWithIdResponse *tns__selectMediaTokenWithIdResponse_);

	/// Web service operation 'selectRelatedMediaAnnotationsWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectRelatedMediaAnnotationsWithTokenId(tns__selectRelatedMediaAnnotationsWithTokenId *tns__selectRelatedMediaAnnotationsWithTokenId_, tns__selectRelatedMediaAnnotationsWithTokenIdResponse *tns__selectRelatedMediaAnnotationsWithTokenIdResponse_) { return selectRelatedMediaAnnotationsWithTokenId(NULL, NULL, tns__selectRelatedMediaAnnotationsWithTokenId_, tns__selectRelatedMediaAnnotationsWithTokenIdResponse_); }
	virtual	int selectRelatedMediaAnnotationsWithTokenId(const char *endpoint, const char *soap_action, tns__selectRelatedMediaAnnotationsWithTokenId *tns__selectRelatedMediaAnnotationsWithTokenId_, tns__selectRelatedMediaAnnotationsWithTokenIdResponse *tns__selectRelatedMediaAnnotationsWithTokenIdResponse_);

	/// Web service operation 'selectUser' (returns error code or SOAP_OK)
	virtual	int selectUser(tns__selectUser *tns__selectUser_, tns__selectUserResponse *tns__selectUserResponse_) { return selectUser(NULL, NULL, tns__selectUser_, tns__selectUserResponse_); }
	virtual	int selectUser(const char *endpoint, const char *soap_action, tns__selectUser *tns__selectUser_, tns__selectUserResponse *tns__selectUserResponse_);

	/// Web service operation 'setUserAnonymous' (returns error code or SOAP_OK)
	virtual	int setUserAnonymous(tns__setUserAnonymous *tns__setUserAnonymous_, tns__setUserAnonymousResponse *tns__setUserAnonymousResponse_) { return setUserAnonymous(NULL, NULL, tns__setUserAnonymous_, tns__setUserAnonymousResponse_); }
	virtual	int setUserAnonymous(const char *endpoint, const char *soap_action, tns__setUserAnonymous *tns__setUserAnonymous_, tns__setUserAnonymousResponse *tns__setUserAnonymousResponse_);

	/// Web service operation 'setUserLanguage' (returns error code or SOAP_OK)
	virtual	int setUserLanguage(tns__setUserLanguage *tns__setUserLanguage_, tns__setUserLanguageResponse *tns__setUserLanguageResponse_) { return setUserLanguage(NULL, NULL, tns__setUserLanguage_, tns__setUserLanguageResponse_); }
	virtual	int setUserLanguage(const char *endpoint, const char *soap_action, tns__setUserLanguage *tns__setUserLanguage_, tns__setUserLanguageResponse *tns__setUserLanguageResponse_);

	/// Web service operation 'submitMediaAlias' (returns error code or SOAP_OK)
	virtual	int submitMediaAlias(tns__submitMediaAlias *tns__submitMediaAlias_, tns__submitMediaAliasResponse *tns__submitMediaAliasResponse_) { return submitMediaAlias(NULL, NULL, tns__submitMediaAlias_, tns__submitMediaAliasResponse_); }
	virtual	int submitMediaAlias(const char *endpoint, const char *soap_action, tns__submitMediaAlias *tns__submitMediaAlias_, tns__submitMediaAliasResponse *tns__submitMediaAliasResponse_);

	/// Web service operation 'submitMediaAliasTextAndTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitMediaAliasTextAndTokenDigest(tns__submitMediaAliasTextAndTokenDigest *tns__submitMediaAliasTextAndTokenDigest_, tns__submitMediaAliasTextAndTokenDigestResponse *tns__submitMediaAliasTextAndTokenDigestResponse_) { return submitMediaAliasTextAndTokenDigest(NULL, NULL, tns__submitMediaAliasTextAndTokenDigest_, tns__submitMediaAliasTextAndTokenDigestResponse_); }
	virtual	int submitMediaAliasTextAndTokenDigest(const char *endpoint, const char *soap_action, tns__submitMediaAliasTextAndTokenDigest *tns__submitMediaAliasTextAndTokenDigest_, tns__submitMediaAliasTextAndTokenDigestResponse *tns__submitMediaAliasTextAndTokenDigestResponse_);

	/// Web service operation 'submitMediaAliasTextWithTokenId' (returns error code or SOAP_OK)
	virtual	int submitMediaAliasTextWithTokenId(tns__submitMediaAliasTextWithTokenId *tns__submitMediaAliasTextWithTokenId_, tns__submitMediaAliasTextWithTokenIdResponse *tns__submitMediaAliasTextWithTokenIdResponse_) { return submitMediaAliasTextWithTokenId(NULL, NULL, tns__submitMediaAliasTextWithTokenId_, tns__submitMediaAliasTextWithTokenIdResponse_); }
	virtual	int submitMediaAliasTextWithTokenId(const char *endpoint, const char *soap_action, tns__submitMediaAliasTextWithTokenId *tns__submitMediaAliasTextWithTokenId_, tns__submitMediaAliasTextWithTokenIdResponse *tns__submitMediaAliasTextWithTokenIdResponse_);

	/// Web service operation 'submitMediaAnnotation' (returns error code or SOAP_OK)
	virtual	int submitMediaAnnotation(tns__submitMediaAnnotation *tns__submitMediaAnnotation_, tns__submitMediaAnnotationResponse *tns__submitMediaAnnotationResponse_) { return submitMediaAnnotation(NULL, NULL, tns__submitMediaAnnotation_, tns__submitMediaAnnotationResponse_); }
	virtual	int submitMediaAnnotation(const char *endpoint, const char *soap_action, tns__submitMediaAnnotation *tns__submitMediaAnnotation_, tns__submitMediaAnnotationResponse *tns__submitMediaAnnotationResponse_);

	/// Web service operation 'submitMediaAnnotationTextAndTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitMediaAnnotationTextAndTokenDigest(tns__submitMediaAnnotationTextAndTokenDigest *tns__submitMediaAnnotationTextAndTokenDigest_, tns__submitMediaAnnotationTextAndTokenDigestResponse *tns__submitMediaAnnotationTextAndTokenDigestResponse_) { return submitMediaAnnotationTextAndTokenDigest(NULL, NULL, tns__submitMediaAnnotationTextAndTokenDigest_, tns__submitMediaAnnotationTextAndTokenDigestResponse_); }
	virtual	int submitMediaAnnotationTextAndTokenDigest(const char *endpoint, const char *soap_action, tns__submitMediaAnnotationTextAndTokenDigest *tns__submitMediaAnnotationTextAndTokenDigest_, tns__submitMediaAnnotationTextAndTokenDigestResponse *tns__submitMediaAnnotationTextAndTokenDigestResponse_);

	/// Web service operation 'submitMediaAnnotationTextWithTokenId' (returns error code or SOAP_OK)
	virtual	int submitMediaAnnotationTextWithTokenId(tns__submitMediaAnnotationTextWithTokenId *tns__submitMediaAnnotationTextWithTokenId_, tns__submitMediaAnnotationTextWithTokenIdResponse *tns__submitMediaAnnotationTextWithTokenIdResponse_) { return submitMediaAnnotationTextWithTokenId(NULL, NULL, tns__submitMediaAnnotationTextWithTokenId_, tns__submitMediaAnnotationTextWithTokenIdResponse_); }
	virtual	int submitMediaAnnotationTextWithTokenId(const char *endpoint, const char *soap_action, tns__submitMediaAnnotationTextWithTokenId *tns__submitMediaAnnotationTextWithTokenId_, tns__submitMediaAnnotationTextWithTokenIdResponse *tns__submitMediaAnnotationTextWithTokenIdResponse_);

	/// Web service operation 'submitMediaToken' (returns error code or SOAP_OK)
	virtual	int submitMediaToken(tns__submitMediaToken *tns__submitMediaToken_, tns__submitMediaTokenResponse *tns__submitMediaTokenResponse_) { return submitMediaToken(NULL, NULL, tns__submitMediaToken_, tns__submitMediaTokenResponse_); }
	virtual	int submitMediaToken(const char *endpoint, const char *soap_action, tns__submitMediaToken *tns__submitMediaToken_, tns__submitMediaTokenResponse *tns__submitMediaTokenResponse_);

	/// Web service operation 'submitMediaTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitMediaTokenDigest(tns__submitMediaTokenDigest *tns__submitMediaTokenDigest_, tns__submitMediaTokenDigestResponse *tns__submitMediaTokenDigestResponse_) { return submitMediaTokenDigest(NULL, NULL, tns__submitMediaTokenDigest_, tns__submitMediaTokenDigestResponse_); }
	virtual	int submitMediaTokenDigest(const char *endpoint, const char *soap_action, tns__submitMediaTokenDigest *tns__submitMediaTokenDigest_, tns__submitMediaTokenDigestResponse *tns__submitMediaTokenDigestResponse_);

	/// Web service operation 'updateMediaAnnotationTextWithId' (returns error code or SOAP_OK)
	virtual	int updateMediaAnnotationTextWithId(tns__updateMediaAnnotationTextWithId *tns__updateMediaAnnotationTextWithId_, tns__updateMediaAnnotationTextWithIdResponse *tns__updateMediaAnnotationTextWithIdResponse_) { return updateMediaAnnotationTextWithId(NULL, NULL, tns__updateMediaAnnotationTextWithId_, tns__updateMediaAnnotationTextWithIdResponse_); }
	virtual	int updateMediaAnnotationTextWithId(const char *endpoint, const char *soap_action, tns__updateMediaAnnotationTextWithId *tns__updateMediaAnnotationTextWithId_, tns__updateMediaAnnotationTextWithIdResponse *tns__updateMediaAnnotationTextWithIdResponse_);
};

} // namespace ServerSoap

#endif
