#ifndef _CORE_MEDIASERVER_H
#define _CORE_MEDIASERVER_H

// core/mediaserver.h
// 8/9/2011

//#define CORE_MS_API_            "http://annot.me:8080/api/"
#define CORE_MS_API_            "http://localhost:8080/api/"
#define CORE_MS_API_LOGIN       CORE_MS_API_ "login.jsp"
#define CORE_MS_API_LOGOUT      CORE_MS_API_ "logout.jsp"
#define CORE_MS_API_ANNOT       CORE_MS_API_ "annot.jsp"
#define CORE_MS_API_TOKEN       CORE_MS_API_ "token.jsp"
#define CORE_MS_API_USER        CORE_MS_API_ "user.jsp"

#define CORE_MS_ATTRIBUTE_ID    "id"
#define CORE_MS_TAG_UNIVERSE    "Universe"
#define CORE_MS_TAG_MEDIATOKEN  "MediaToken"
#define CORE_MS_TAG_MEDIAANNOT  "MediaAnnot"
#define CORE_MS_TAG_MEDIAUSER   "UniverseUser"
#define CORE_MS_TAG_ANNOT       "Annot"
#define CORE_MS_TAG_TOKEN       "Token"
#define CORE_MS_TAG_USER        "User"
#define CORE_MS_TAG_TOKENID     "TokenId"
#define CORE_MS_TAG_USERID      "UserId"
#define CORE_MS_TAG_NAME        "Name"
#define CORE_MS_TAG_NICKNAME    "NickName"
#define CORE_MS_TAG_EMAIL       "Email"
#define CORE_MS_TAG_CREATETIME  "CreateTime"
#define CORE_MS_TAG_UPDATETIME  "UpdateTime"
#define CORE_MS_TAG_LOGINTIME   "LoginTime"
#define CORE_MS_TAG_LANGUAGE    "Language"
#define CORE_MS_TAG_POS         "Pos"
#define CORE_MS_TAG_TEXT        "Text"
#define CORE_MS_TAG_DIGEST      "Digest"
#define CORE_MS_TAG_SCORE       "Score"
#define CORE_MS_TAG_LEVEL       "Level"
#define CORE_MS_TAG_BLESSEDCOUNT "BlessedCount"
#define CORE_MS_TAG_CURSEDCOUNT "CursedCount"
#define CORE_MS_TAG_KILLEDCOUNT "KilledCount"
#define CORE_MS_TAG_VISITEDCOUNT "VisitedCount"
#define CORE_MS_TAG_ERROR       "Error"
#define CORE_MS_TAG_ERRORCODE   "ErrorCode"
#define CORE_MS_TAG_ERRORREASON "ErrorReason"
#define CORE_MS_TAG_ERRORDETAIL "ErrorDetail"
#define CORE_MS_TAG_ERRORHELP   "ErrorHelp"

#define CORE_MS_ACTION_SUBMIT   "submit"
#define CORE_MS_ACTION_QUERY    "query"
#define CORE_MS_ACTION_CLUSTER  "cluster"
#define CORE_MS_ACTION_LOGIN    "login"
#define CORE_MS_ACTION_LOGOUT   "logout"
#define CORE_MS_DOMAIN_MEDIA    "media"
#define CORE_MS_QUERY_DOMAIN    "domain"
#define CORE_MS_QUERY_ACTION    "action"
#define CORE_MS_QUERY_STATUS    "status"
#define CORE_MS_QUERY_LANGUAGE  "language "
#define CORE_MS_QUERY_ANNOTID   "annotid"
#define CORE_MS_QUERY_USERID    "userid"
#define CORE_MS_QUERY_USERNAME  "username"
#define CORE_MS_QUERY_NICKNAME  "nickname"
#define CORE_MS_QUERY_EMAIL     "email"
#define CORE_MS_QUERY_PASSWORD  "password"
#define CORE_MS_QUERY_TOKENID   "tokenid"
#define CORE_MS_QUERY_CREATETIME "createtime"
#define CORE_MS_QUERY_UPDATETIME "updatetime"
#define CORE_MS_QUERY_POS       "pos"
#define CORE_MS_QUERY_TEXT      "text"
#define CORE_MS_QUERY_DIGEST    "digest"
#define CORE_MS_QUERY_SOURCE    "source"
#define CORE_MS_QUERY_BLESSED   "blessed"
#define CORE_MS_QUERY_CURSED    "cursed"
#define CORE_MS_QUERY_KILLED    "killed"
#define CORE_MS_QUERY_VISITED   "visited"

#endif // _CORE_MEDIASERVER_H
