#ifndef RC_H
#define RC_H

// rc.h
// 7/15/2011
#include "project/common/acrc.h"

#define RC_NULL         ACRC_NULL

#define RC_PREFIX_IMAGE ":/images/"
#define RC_IMAGE_NULL   RC_NULL

#define RC_PREFIX_TR    ":/tr/"
#define RC_TR_NULL      RC_NULL

// - Translations -

#define RC_TR_EN        RC_PREFIX_TR "tr_en"
#define RC_TR_JA        RC_PREFIX_TR "tr_ja"
#define RC_TR_ZH_TW     RC_PREFIX_TR "tr_zh_TW"
#define RC_TR_ZH_CN     RC_PREFIX_TR "tr_zh_CN"

// - Apps -

#define RC_IMAGE_APP            ACRC_IMAGE_PLAYER

// - Backgrounds -

#define RC_IMAGE_AERO_DARK      RC_PREFIX_IMAGE "aero_dark.jpg"
#define RC_IMAGE_AERO_BLACK     RC_PREFIX_IMAGE "aero_black.jpg"
#define RC_IMAGE_AERO_BLUE      RC_PREFIX_IMAGE "aero_blue.jpg"
#define RC_IMAGE_AERO_BROWN     RC_PREFIX_IMAGE "aero_brown.jpg"
#define RC_IMAGE_AERO_CYAN      RC_PREFIX_IMAGE "aero_cyan.jpg"
#define RC_IMAGE_AERO_GRAY      RC_PREFIX_IMAGE "aero_gray.jpg"
#define RC_IMAGE_AERO_GREEN     RC_PREFIX_IMAGE "aero_green.jpg"
#define RC_IMAGE_AERO_PINK      RC_PREFIX_IMAGE "aero_pink.jpg"
#define RC_IMAGE_AERO_PURPLE    RC_PREFIX_IMAGE "aero_purple.jpg"
#define RC_IMAGE_AERO_RED       RC_PREFIX_IMAGE "aero_red.jpg"
#define RC_IMAGE_AERO_WHITE     RC_PREFIX_IMAGE "aero_white.jpg"
#define RC_IMAGE_AERO_YELLOW    RC_PREFIX_IMAGE "aero_yellow.jpg"

#define RC_IMAGE_AERO_DARK_PREVIEW      RC_PREFIX_IMAGE "aero_dark_thumbnail.png"
#define RC_IMAGE_AERO_BLACK_PREVIEW     RC_PREFIX_IMAGE "aero_black_thumbnail.png"
#define RC_IMAGE_AERO_BLUE_PREVIEW      RC_PREFIX_IMAGE "aero_blue_thumbnail.png"
#define RC_IMAGE_AERO_BROWN_PREVIEW     RC_PREFIX_IMAGE "aero_brown_thumbnail.png"
#define RC_IMAGE_AERO_CYAN_PREVIEW      RC_PREFIX_IMAGE "aero_cyan_thumbnail.png"
#define RC_IMAGE_AERO_GRAY_PREVIEW      RC_PREFIX_IMAGE "aero_gray_thumbnail.png"
#define RC_IMAGE_AERO_GREEN_PREVIEW     RC_PREFIX_IMAGE "aero_green_thumbnail.png"
#define RC_IMAGE_AERO_PINK_PREVIEW      RC_PREFIX_IMAGE "aero_pink_thumbnail.png"
#define RC_IMAGE_AERO_PURPLE_PREVIEW    RC_PREFIX_IMAGE "aero_purple_thumbnail.png"
#define RC_IMAGE_AERO_RED_PREVIEW       RC_PREFIX_IMAGE "aero_red_thumbnail.png"
#define RC_IMAGE_AERO_WHITE_PREVIEW     RC_PREFIX_IMAGE "aero_white_thumbnail.png"
#define RC_IMAGE_AERO_YELLOW_PREVIEW    RC_PREFIX_IMAGE "aero_yellow_thumbnail.png"

// - Buttons -
#define RC_IMAGE_PLAY_HOVER     RC_PREFIX_IMAGE "play.png"
#define RC_IMAGE_PLAY           RC_PREFIX_IMAGE "play_hover.png"        // Highlight play button
#define RC_IMAGE_PLAY_PRESSED   RC_PREFIX_IMAGE "play_pressed.png"
#define RC_IMAGE_PLAY_DISABLED  RC_PREFIX_IMAGE "play_disabled.png"
#define RC_IMAGE_PLAY_CHECKED   RC_PREFIX_IMAGE "play_checked.png"
#define RC_IMAGE_PLAY_CHECKED_HOVER RC_IMAGE_PLAY_HOVER
#define RC_IMAGE_STOP           RC_PREFIX_IMAGE "stop.png"
#define RC_IMAGE_STOP_HOVER     RC_PREFIX_IMAGE "stop_hover.png"
#define RC_IMAGE_STOP_PRESSED   RC_PREFIX_IMAGE "stop_pressed.png"
#define RC_IMAGE_STOP_DISABLED  RC_PREFIX_IMAGE "stop_disabled.png"
#define RC_IMAGE_STOP_CHECKED   RC_PREFIX_IMAGE "stop_checked.png"
#define RC_IMAGE_STOP_CHECKED_HOVER RC_IMAGE_STOP_HOVER
#define RC_IMAGE_PAUSE          RC_PREFIX_IMAGE "pause.png"
#define RC_IMAGE_PAUSE_HOVER    RC_PREFIX_IMAGE "pause_hover.png"
#define RC_IMAGE_PAUSE_PRESSED  RC_PREFIX_IMAGE "pause_pressed.png"
#define RC_IMAGE_PAUSE_DISABLED RC_PREFIX_IMAGE "pause_disabled.png"
#define RC_IMAGE_PAUSE_CHECKED  RC_PREFIX_IMAGE "pause_checked.png"
#define RC_IMAGE_PAUSE_CHECKED_HOVER RC_IMAGE_PAUSE_HOVER
#define RC_IMAGE_OPEN           RC_PREFIX_IMAGE "open.png"
#define RC_IMAGE_OPEN_HOVER     RC_PREFIX_IMAGE "open_hover.png"
#define RC_IMAGE_OPEN_PRESSED   RC_PREFIX_IMAGE "open_pressed.png"
#define RC_IMAGE_OPEN_DISABLED  RC_PREFIX_IMAGE "open_disabled.png"
#define RC_IMAGE_OPEN_CHECKED   RC_PREFIX_IMAGE "open_checked.png"
#define RC_IMAGE_OPEN_CHECKED_HOVER RC_IMAGE_OPEN_HOVER
#define RC_IMAGE_NEXTFRAME              RC_PREFIX_IMAGE "nextframe.png"
#define RC_IMAGE_NEXTFRAME_HOVER        RC_PREFIX_IMAGE "nextframe_hover.png"
#define RC_IMAGE_NEXTFRAME_PRESSED      RC_PREFIX_IMAGE "nextframe_pressed.png"
#define RC_IMAGE_NEXTFRAME_DISABLED     RC_PREFIX_IMAGE "nextframe_disabled.png"
#define RC_IMAGE_NEXTFRAME_CHECKED      RC_PREFIX_IMAGE "nextframe_checked.png"
#define RC_IMAGE_NEXTFRAME_CHECKED_HOVER RC_IMAGE_NEXTFRAME_HOVER
#define RC_IMAGE_FASTFORWARD            RC_PREFIX_IMAGE "fastforward.png"
#define RC_IMAGE_FASTFORWARD_HOVER      RC_PREFIX_IMAGE "fastforward_hover.png"
#define RC_IMAGE_FASTFORWARD_PRESSED    RC_PREFIX_IMAGE "fastforward_pressed.png"
#define RC_IMAGE_FASTFORWARD_DISABLED   RC_PREFIX_IMAGE "fastforward_disabled.png"
#define RC_IMAGE_FASTFORWARD_CHECKED    RC_PREFIX_IMAGE "fastforward_checked.png"
#define RC_IMAGE_FASTFORWARD_CHECKED_HOVER RC_IMAGE_FASTFORWARD_HOVER
#define RC_IMAGE_FASTFASTFORWARD            RC_PREFIX_IMAGE "fastfastforward.png"
#define RC_IMAGE_FASTFASTFORWARD_HOVER      RC_PREFIX_IMAGE "fastfastforward_hover.png"
#define RC_IMAGE_FASTFASTFORWARD_PRESSED    RC_PREFIX_IMAGE "fastfastforward_pressed.png"
#define RC_IMAGE_FASTFASTFORWARD_DISABLED   RC_PREFIX_IMAGE "fastfastforward_disabled.png"
#define RC_IMAGE_FASTFASTFORWARD_CHECKED    RC_PREFIX_IMAGE "fastfastforward_checked.png"
#define RC_IMAGE_FASTFASTFORWARD_CHECKED_HOVER RC_IMAGE_FASTFASTFORWARD_HOVER
#define RC_IMAGE_REWIND                 RC_PREFIX_IMAGE "rewind.png"
#define RC_IMAGE_REWIND_HOVER           RC_PREFIX_IMAGE "rewind_hover.png"
#define RC_IMAGE_REWIND_PRESSED         RC_PREFIX_IMAGE "rewind_pressed.png"
#define RC_IMAGE_REWIND_DISABLED        RC_PREFIX_IMAGE "rewind_disabled.png"
#define RC_IMAGE_REWIND_CHECKED         RC_PREFIX_IMAGE "rewind_checked.png"
#define RC_IMAGE_REWIND_CHECKED_HOVER RC_IMAGE_REWIND_HOVER
#define RC_IMAGE_EMBED          RC_PREFIX_IMAGE "E.png"
#define RC_IMAGE_EMBED_HOVER    RC_PREFIX_IMAGE "E_hover.png"
#define RC_IMAGE_EMBED_PRESSED  RC_PREFIX_IMAGE "E_pressed.png"
#define RC_IMAGE_EMBED_DISABLED RC_PREFIX_IMAGE "E_disabled.png"
#define RC_IMAGE_EMBED_CHECKED  RC_PREFIX_IMAGE "E_checked.png"
#define RC_IMAGE_EMBED_CHECKED_HOVER RC_IMAGE_EMBED_HOVER
#define RC_IMAGE_MINI           RC_PREFIX_IMAGE "M.png"
#define RC_IMAGE_MINI_HOVER     RC_PREFIX_IMAGE "M_hover.png"
#define RC_IMAGE_MINI_PRESSED   RC_PREFIX_IMAGE "M_pressed.png"
#define RC_IMAGE_MINI_DISABLED  RC_PREFIX_IMAGE "M_disabled.png"
#define RC_IMAGE_MINI_CHECKED   RC_PREFIX_IMAGE "M_checked.png"
#define RC_IMAGE_MINI_CHECKED_HOVER RC_IMAGE_MINI_HOVER
#define RC_IMAGE_FULLSCREEN             RC_PREFIX_IMAGE "F.png"
#define RC_IMAGE_FULLSCREEN_HOVER       RC_PREFIX_IMAGE "F_hover.png"
#define RC_IMAGE_FULLSCREEN_PRESSED     RC_PREFIX_IMAGE "F_pressed.png"
#define RC_IMAGE_FULLSCREEN_DISABLED    RC_PREFIX_IMAGE "F_disabled.png"
#define RC_IMAGE_FULLSCREEN_CHECKED     RC_PREFIX_IMAGE "F_checked.png"
#define RC_IMAGE_FULLSCREEN_CHECKED_HOVER RC_IMAGE_FULLSCREEN_HOVER
#define RC_IMAGE_TRACE             RC_PREFIX_IMAGE "T.png"
#define RC_IMAGE_TRACE_HOVER       RC_PREFIX_IMAGE "T_hover.png"
#define RC_IMAGE_TRACE_PRESSED     RC_PREFIX_IMAGE "T_pressed.png"
#define RC_IMAGE_TRACE_DISABLED    RC_PREFIX_IMAGE "T_disabled.png"
#define RC_IMAGE_TRACE_CHECKED     RC_PREFIX_IMAGE "T_checked.png"
#define RC_IMAGE_TRACE_CHECKED_HOVER RC_IMAGE_TRACE_HOVER
#define RC_IMAGE_ACTUALSIZE             RC_PREFIX_IMAGE "fullscreen.png"
#define RC_IMAGE_ACTUALSIZE_HOVER       RC_PREFIX_IMAGE "fullscreen_hover.png"
#define RC_IMAGE_ACTUALSIZE_PRESSED     RC_PREFIX_IMAGE "fullscreen_pressed.png"
#define RC_IMAGE_ACTUALSIZE_DISABLED    RC_PREFIX_IMAGE "fullscreen_disabled.png"
#define RC_IMAGE_ACTUALSIZE_CHECKED     RC_PREFIX_IMAGE "fullscreen_checked.png"
#define RC_IMAGE_ACTUALSIZE_CHECKED_HOVER RC_IMAGE_ACTUALSIZE_HOVER
#define RC_IMAGE_ANNOT                  RC_PREFIX_IMAGE "comment.png"
#define RC_IMAGE_ANNOT_HOVER            RC_PREFIX_IMAGE "comment_hover.png"
#define RC_IMAGE_ANNOT_PRESSED          RC_PREFIX_IMAGE "comment_pressed.png"
#define RC_IMAGE_ANNOT_DISABLED         RC_PREFIX_IMAGE "comment_disabled.png"
#define RC_IMAGE_ANNOT_CHECKED          RC_PREFIX_IMAGE "comment_checked.png"
#define RC_IMAGE_ANNOT_CHECKED_HOVER RC_IMAGE_ANNOT_HOVER
#define RC_IMAGE_SHOWANNOT              RC_IMAGE_ANNOT_HOVER
#define RC_IMAGE_SHOWANNOT_HOVER        RC_IMAGE_ANNOT
#define RC_IMAGE_SHOWANNOT_PRESSED      RC_IMAGE_ANNOT_PRESSED
#define RC_IMAGE_SHOWANNOT_DISABLED     RC_IMAGE_ANNOT_DISABLED
#define RC_IMAGE_SHOWANNOT_CHECKED      RC_IMAGE_ANNOT_CHECKED
#define RC_IMAGE_SHOWANNOT_CHECKED_HOVER RC_IMAGE_SHOWANNOT_HOVER
#define RC_IMAGE_HIDEANNOT              RC_IMAGE_ANNOT
#define RC_IMAGE_HIDEANNOT_HOVER        RC_IMAGE_ANNOT_HOVER
#define RC_IMAGE_HIDEANNOT_PRESSED      RC_IMAGE_ANNOT_PRESSED
#define RC_IMAGE_HIDEANNOT_DISABLED     RC_IMAGE_ANNOT_DISABLED
#define RC_IMAGE_HIDEANNOT_CHECKED      RC_IMAGE_ANNOT_CHECKED
#define RC_IMAGE_HIDEANNOT_CHECKED_HOVER RC_IMAGE_HIDEANNOT_HOVER
#define RC_IMAGE_USER                   RC_IMAGE_NULL
#define RC_IMAGE_USER_HOVER             RC_IMAGE_NULL
#define RC_IMAGE_USER_PRESSED           RC_IMAGE_NULL
#define RC_IMAGE_USER_DISABLED          RC_IMAGE_NULL
#define RC_IMAGE_USER_CHECKED           RC_IMAGE_NULL
#define RC_IMAGE_USER_CHECKED_HOVER RC_IMAGE_USER_HOVER
#define RC_IMAGE_SNAPSHOT               RC_IMAGE_NULL
#define RC_IMAGE_SNAPSHOT_HOVER         RC_IMAGE_NULL
#define RC_IMAGE_SNAPSHOT_PRESSED       RC_IMAGE_NULL
#define RC_IMAGE_SNAPSHOT_DISABLED      RC_IMAGE_NULL
#define RC_IMAGE_SNAPSHOT_CHECKED       RC_IMAGE_NULL
#define RC_IMAGE_SNAPSHOT_CHECKED_HOVER RC_IMAGE_SNAPSHOT_HOVER
#define RC_IMAGE_MENU                   RC_PREFIX_IMAGE "menu.png"
#define RC_IMAGE_MENU_HOVER             RC_PREFIX_IMAGE "menu_hover.png"
#define RC_IMAGE_MENU_PRESSED           RC_PREFIX_IMAGE "menu_pressed.png"
#define RC_IMAGE_MENU_DISABLED          RC_PREFIX_IMAGE "menu_disabled.png"
#define RC_IMAGE_MENU_CHECKED           RC_PREFIX_IMAGE "menu_checked.png"
#define RC_IMAGE_MENU_CHECKED_HOVER RC_IMAGE_MENU_HOVER
#define RC_IMAGE_PREVIOUS               RC_PREFIX_IMAGE "previous.png"
#define RC_IMAGE_PREVIOUS_HOVER         RC_PREFIX_IMAGE "previous_hover.png"
#define RC_IMAGE_PREVIOUS_PRESSED       RC_PREFIX_IMAGE "previous_pressed.png"
#define RC_IMAGE_PREVIOUS_DISABLED      RC_PREFIX_IMAGE "previous_disabled.png"
#define RC_IMAGE_PREVIOUS_CHECKED       RC_PREFIX_IMAGE "previous_checked.png"
#define RC_IMAGE_PREVIOUS_CHECKED_HOVER RC_IMAGE_PREVIOUS_HOVER
#define RC_IMAGE_NEXT                   RC_PREFIX_IMAGE "next.png"
#define RC_IMAGE_NEXT_HOVER             RC_PREFIX_IMAGE "next_hover.png"
#define RC_IMAGE_NEXT_PRESSED           RC_PREFIX_IMAGE "next_pressed.png"
#define RC_IMAGE_NEXT_DISABLED          RC_PREFIX_IMAGE "next_disabled.png"
#define RC_IMAGE_NEXT_CHECKED           RC_PREFIX_IMAGE "next_checked.png"
#define RC_IMAGE_NEXT_CHECKED_HOVER RC_IMAGE_NEXT_HOVER
#define RC_IMAGE_SYNC           RC_PREFIX_IMAGE "sync.png"
#define RC_IMAGE_SYNC_HOVER     RC_PREFIX_IMAGE "sync_hover.png"
#define RC_IMAGE_SYNC_PRESSED   RC_PREFIX_IMAGE "sync_pressed.png"
#define RC_IMAGE_SYNC_DISABLED  RC_PREFIX_IMAGE "sync_disabled.png"
#define RC_IMAGE_SYNC_CHECKED   RC_PREFIX_IMAGE "sync_checked.png"
#define RC_IMAGE_SYNC_CHECKED_HOVER RC_IMAGE_SYNC_HOVER
//#define RC_IMAGE_LIVE           RC_PREFIX_IMAGE "live.png"
//#define RC_IMAGE_LIVE_HOVER     RC_PREFIX_IMAGE "live_hover.png"
//#define RC_IMAGE_LIVE_PRESSED   RC_PREFIX_IMAGE "live_pressed.png"
//#define RC_IMAGE_LIVE_DISABLED  RC_PREFIX_IMAGE "live_disabled.png"
//#define RC_IMAGE_LIVE_CHECKED   RC_PREFIX_IMAGE "live_checked.png"
//#define RC_IMAGE_LIVE_CHECKED_HOVER RC_IMAGE_LIVE_HOVER
#define RC_IMAGE_LIVE   RC_IMAGE_NULL

#define RC_IMAGE_DOWNARROW              RC_PREFIX_IMAGE "downarrow.png"
#define RC_IMAGE_DOWNARROW_HOVER        RC_PREFIX_IMAGE "downarrow_hover.png"
#define RC_IMAGE_DOWNARROW_PRESSED      RC_PREFIX_IMAGE "downarrow_pressed.png"
#define RC_IMAGE_DOWNARROW_DISABLED     RC_PREFIX_IMAGE "downarrow_disabled.png"
#define RC_IMAGE_DOWNARROW_CHECKED      RC_PREFIX_IMAGE "downarrow_checked.png"
#define RC_IMAGE_DOWNARROW_CHECKED_HOVER RC_IMAGE_DOWNARROW_HOVER

#define RC_IMAGE_UPARROW                RC_PREFIX_IMAGE "uparrow.png"
#define RC_IMAGE_UPARROW_HOVER          RC_PREFIX_IMAGE "uparrow_hover.png"
#define RC_IMAGE_UPARROW_PRESSED        RC_PREFIX_IMAGE "uparrow_pressed.png"
#define RC_IMAGE_UPARROW_DISABLED       RC_PREFIX_IMAGE "uparrow_disabled.png"
#define RC_IMAGE_UPARROW_CHECKED        RC_PREFIX_IMAGE "uparrow_checked.png"
#define RC_IMAGE_UPARROW_CHECKED_HOVER RC_IMAGE_UPARROW_HOVER

#define RC_IMAGE_MAXIMIZE                RC_PREFIX_IMAGE "maximize.png"
#define RC_IMAGE_MAXIMIZE_HOVER          RC_PREFIX_IMAGE "maximize_hover.png"
#define RC_IMAGE_MAXIMIZE_PRESSED        RC_PREFIX_IMAGE "maximize_pressed.png"
#define RC_IMAGE_MAXIMIZE_DISABLED       RC_PREFIX_IMAGE "maximize_disabled.png"
#define RC_IMAGE_MAXIMIZE_CHECKED        RC_PREFIX_IMAGE "maximize_checked.png"
#define RC_IMAGE_MAXIMIZE_CHECKED_HOVER RC_IMAGE_MAXIMIZE_HOVER

#define RC_IMAGE_MINIMIZE                RC_PREFIX_IMAGE "minimize.png"
#define RC_IMAGE_MINIMIZE_HOVER          RC_PREFIX_IMAGE "minimize_hover.png"
#define RC_IMAGE_MINIMIZE_PRESSED        RC_PREFIX_IMAGE "minimize_pressed.png"
#define RC_IMAGE_MINIMIZE_DISABLED       RC_PREFIX_IMAGE "minimize_disabled.png"
#define RC_IMAGE_MINIMIZE_CHECKED        RC_PREFIX_IMAGE "minimize_checked.png"
#define RC_IMAGE_MINIMIZE_CHECKED_HOVER RC_IMAGE_MINIMIZE_HOVER

#define RC_IMAGE_RESTORE                RC_PREFIX_IMAGE "restore.png"
#define RC_IMAGE_RESTORE_HOVER          RC_PREFIX_IMAGE "restore_hover.png"
#define RC_IMAGE_RESTORE_PRESSED        RC_PREFIX_IMAGE "restore_pressed.png"
#define RC_IMAGE_RESTORE_DISABLED       RC_PREFIX_IMAGE "restore_disabled.png"
#define RC_IMAGE_RESTORE_CHECKED        RC_PREFIX_IMAGE "restore_checked.png"
#define RC_IMAGE_RESTORE_CHECKED_HOVER RC_IMAGE_RESTORE_HOVER

// TODO
#define RC_IMAGE_SEEK           RC_IMAGE_NULL
#define RC_IMAGE_REPLAY         RC_IMAGE_NULL

#define RC_IMAGE_PREVIOUSSECTION RC_IMAGE_PREVIOUS
#define RC_IMAGE_NEXTSECTION     RC_IMAGE_NEXT

#define RC_IMAGE_ENABLEBLACKLIST      RC_IMAGE_NULL
#define RC_IMAGE_BLACKLIST      RC_IMAGE_NULL
#define RC_IMAGE_BACKLOG        RC_IMAGE_NULL
#define RC_IMAGE_DOWNLOAD       RC_IMAGE_NULL
#define RC_IMAGE_CONSOLE        RC_IMAGE_NULL
#define RC_IMAGE_SECTION        RC_IMAGE_NULL
#define RC_IMAGE_CURRENTSECTION RC_IMAGE_PLAY
#define RC_IMAGE_SUBTITLE       RC_IMAGE_NULL
#define RC_IMAGE_AUDIOTRACK     RC_IMAGE_NULL
#define RC_IMAGE_ANNOTSUBTITLE  RC_IMAGE_NULL
#define RC_IMAGE_SUBANNOT       RC_IMAGE_NULL
#define RC_IMAGE_NONSUBANNOT    RC_IMAGE_NULL
#define RC_IMAGE_SHOWSUBTITLE   RC_IMAGE_SUBTITLE
#define RC_IMAGE_HIDESUBTITLE   RC_IMAGE_SUBTITLE
#define RC_IMAGE_CURRENTSUBTITLE RC_IMAGE_PLAY
#define RC_IMAGE_CURRENTFILE    RC_IMAGE_PLAY
#define RC_IMAGE_CURRENTTRACK   RC_IMAGE_PLAY
#define RC_IMAGE_SHOWMENUBAR    RC_IMAGE_NULL
#define RC_IMAGE_ENABLEAERO     RC_IMAGE_NULL
#define RC_IMAGE_DISABLEAERO    RC_IMAGE_NULL
#define RC_IMAGE_MENUTHEME      RC_IMAGE_NULL

#define RC_IMAGE_FORWARD        RC_IMAGE_NULL
#define RC_IMAGE_BACKWARD       RC_IMAGE_NULL
#define RC_IMAGE_FORWARD5S      RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD5S     RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD10S     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD10S    RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD25S     RC_IMAGE_FORWARD
#define RC_IMAGE_FORWARD30S     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD30S    RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD60S     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD60S    RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD85S     RC_IMAGE_FORWARD
#define RC_IMAGE_FORWARD90S     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD90S    RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD1M      RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD1M     RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD5M      RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD5M     RC_IMAGE_BACKWARD
#define RC_IMAGE_FORWARD10M     RC_IMAGE_FORWARD
#define RC_IMAGE_BACKWARD10M    RC_IMAGE_BACKWARD

#define RC_IMAGE_LOGO   RC_IMAGE_NULL
#define RC_IMAGE_QUIT   RC_IMAGE_NULL
#define RC_IMAGE_ABOUT  RC_IMAGE_NULL
#define RC_IMAGE_HELP   RC_IMAGE_NULL
#define RC_IMAGE_UPDATE RC_IMAGE_NULL

#define RC_IMAGE_LOGIN  RC_IMAGE_NULL
#define RC_IMAGE_LOGOUT RC_IMAGE_NULL

#define RC_IMAGE_COPY   RC_IMAGE_NULL
#define RC_IMAGE_PASTE  RC_IMAGE_NULL

#define RC_IMAGE_ENABLEAUTOCLEARCONSOLE         RC_IMAGE_NULL
#define RC_IMAGE_DISABLEAUTOCLEARCONSOLE        RC_IMAGE_NULL

#define RC_IMAGE_SEEKDIALOG     RC_IMAGE_NULL
#define RC_IMAGE_LOGINDIALOG    RC_IMAGE_NULL
#define RC_IMAGE_LIVEDIALOG     RC_IMAGE_NULL
#define RC_IMAGE_SYNCDIALOG     RC_IMAGE_NULL

#define RC_IMAGE_PICKDIALOG     RC_IMAGE_NULL
#define RC_IMAGE_WINDOWPICKDIALOG       RC_IMAGE_NULL
#define RC_IMAGE_PROCESSPICKDIALOG      RC_IMAGE_NULL

#define RC_IMAGE_OPENCONTEXTMENU RC_IMAGE_NULL
#define RC_IMAGE_OPENFILE       RC_IMAGE_NULL
#define RC_IMAGE_OPENURL        RC_IMAGE_NULL
#define RC_IMAGE_OPENANNOTATIONURL RC_IMAGE_NULL
#define RC_IMAGE_OPENDEVICE     RC_IMAGE_OPEN
#define RC_IMAGE_OPENVIDEODEVICE RC_IMAGE_NULL
#define RC_IMAGE_OPENAUDIODEVICE RC_IMAGE_NULL
#define RC_IMAGE_OPENSUBTITLE   RC_IMAGE_NULL

#define RC_IMAGE_ADVANCED       RC_IMAGE_NULL
#define RC_IMAGE_CLEARCACHE     RC_IMAGE_NULL

#define RC_IMAGE_CONNECT        RC_IMAGE_NULL
#define RC_IMAGE_DISCONNECT     RC_IMAGE_NULL

#define RC_IMAGE_WINDOWSTAYSONTOP RC_IMAGE_NULL
#define RC_IMAGE_EMBEDONTOP     RC_IMAGE_NULL

#define RC_IMAGE_ANNOTATIONBROWSER RC_IMAGE_NULL
#define RC_IMAGE_ANNOTATIONEDITOR RC_IMAGE_NULL
#define RC_IMAGE_TOKENVIEW      RC_IMAGE_NULL
#define RC_IMAGE_COMMENTVIEW    RC_IMAGE_NULL
#define RC_IMAGE_PROXYVIEW      RC_IMAGE_NULL
#define RC_IMAGE_SIGNALVIEW     RC_IMAGE_NULL
#define RC_IMAGE_SITEACCOUNT    RC_IMAGE_NULL
#define RC_IMAGE_MEDIAINFO      RC_IMAGE_NULL

#define RC_IMAGE_EDIT           RC_IMAGE_NULL
#define RC_IMAGE_HIDE           RC_IMAGE_NULL
#define RC_IMAGE_SHOW           RC_IMAGE_NULL
#define RC_IMAGE_BLOCK          RC_IMAGE_NULL
#define RC_IMAGE_BLESS          RC_IMAGE_NULL
#define RC_IMAGE_CURSE          RC_IMAGE_NULL
#define RC_IMAGE_VIEW           RC_IMAGE_NULL
#define RC_IMAGE_DELETE         RC_IMAGE_NULL
#define RC_IMAGE_DELETECACHE    RC_IMAGE_NULL

#define RC_IMAGE_EDITTHISANNOT  RC_IMAGE_EDIT
#define RC_IMAGE_BLOCKTHISANNOT RC_IMAGE_BLOCK
#define RC_IMAGE_BLESSTHISANNOT RC_IMAGE_BLESS
#define RC_IMAGE_CURSETHISANNOT RC_IMAGE_CURSE
#define RC_IMAGE_HIDETHISANNOT  RC_IMAGE_HIDE
#define RC_IMAGE_SHOWTHISANNOT  RC_IMAGE_SHOW
#define RC_IMAGE_COPYTHISANNOT  RC_IMAGE_COPY
#define RC_IMAGE_DELETETHISANNOT  RC_IMAGE_DELETE

#define RC_IMAGE_VIEWTHISUSER   RC_IMAGE_VIEW
#define RC_IMAGE_BLOCKTHISUSER  RC_IMAGE_BLOCK

#define RC_IMAGE_REFRESH        RC_IMAGE_NULL
#define RC_IMAGE_REFRESHPROCESS RC_IMAGE_REFRESH
#define RC_IMAGE_ATTACHPROCESS  RC_IMAGE_NULL
#define RC_IMAGE_DETACHPROCESS  RC_IMAGE_NULL

#define RC_IMAGE_RECENTMESSAGES RC_IMAGE_NULL

#define RC_IMAGE_TRANSLATE      RC_IMAGE_NULL

#define RC_IMAGE_ANNOTATIONLIMIT RC_IMAGE_NULL

#define RC_IMAGE_OPENINWEBBROWSER RC_IMAGE_NULL
#define RC_IMAGE_DOWNLOADCURRENT RC_IMAGE_NULL
#define RC_IMAGE_COPYCURRENTURL RC_IMAGE_NULL
#define RC_IMAGE_COPYCURRENTTITLE RC_IMAGE_NULL

#define RC_IMAGE_NETWORKPROXY   RC_IMAGE_NULL

#define RC_IMAGE_CLEAR          RC_IMAGE_NULL
#define RC_IMAGE_HISTORY        RC_IMAGE_NULL

#define RC_IMAGE_RECENT         RC_IMAGE_NULL
#define RC_IMAGE_RECENTFILE     RC_IMAGE_NULL
#define RC_IMAGE_CLEARRECENT    RC_IMAGE_CLEAR

#define RC_IMAGE_CLEARPLAYLIST  RC_IMAGE_CLEAR

#define RC_IMAGE_ENGLISH        ACRC_IMAGE_ENGLISH
#define RC_IMAGE_JAPANESE       ACRC_IMAGE_JAPANESE
#define RC_IMAGE_CHINESE        ACRC_IMAGE_CHINESE
#define RC_IMAGE_KOREAN         ACRC_IMAGE_KOREAN
#define RC_IMAGE_FRENCH         ACRC_IMAGE_FRENCH
#define RC_IMAGE_GERMAN         ACRC_IMAGE_GERMAN
#define RC_IMAGE_ITALIAN        ACRC_IMAGE_ITALIAN
#define RC_IMAGE_SPANISH        ACRC_IMAGE_SPANISH
#define RC_IMAGE_PORTUGUESE     ACRC_IMAGE_PORTUGUESE
#define RC_IMAGE_UKNOWN         RC_IMAGE_NULL
#define RC_IMAGE_UNKNOWNLANGUAGE RC_IMAGE_NULL
#define RC_IMAGE_ANYLANGUAGE    RC_IMAGE_NULL
#define RC_IMAGE_TRADITIONALCHINESE ACRC_IMAGE_ROC
#define RC_IMAGE_SIMPLIFIEDCHINESE  ACRC_IMAGE_PRC

#define RC_IMAGE_ANONYMOUS  RC_IMAGE_NULL
#define RC_IMAGE_CHECKINTERNET  RC_IMAGE_NULL

#define RC_IMAGE_SUBTITLEONTOP  RC_IMAGE_NULL
#define RC_IMAGE_MONITORCLIPBOARD RC_IMAGE_NULL

#define RC_IMAGE_DEFAULTCOLOR   RC_IMAGE_NULL
#define RC_IMAGE_REDCOLOR       RC_IMAGE_NULL
#define RC_IMAGE_WHITECOLOR     RC_IMAGE_NULL
#define RC_IMAGE_CYANCOLOR      RC_IMAGE_NULL
#define RC_IMAGE_BLUECOLOR      RC_IMAGE_NULL
#define RC_IMAGE_PURPLECOLOR    RC_IMAGE_NULL
#define RC_IMAGE_ORANGECOLOR    RC_IMAGE_NULL
#define RC_IMAGE_BLACKCOLOR     RC_IMAGE_NULL

#define RC_IMAGE_DEFAULTTHEME   ACRC_IMAGE_AERO_PREVIEW
#define RC_IMAGE_RANDOMTHEME    ACRC_IMAGE_NULL
#define RC_IMAGE_DARKTHEME      ACRC_IMAGE_AERO_DARK_PREVIEW
#define RC_IMAGE_BLACKTHEME     ACRC_IMAGE_AERO_BLACK_PREVIEW
#define RC_IMAGE_BLUETHEME      ACRC_IMAGE_AERO_BLUE_PREVIEW
#define RC_IMAGE_BROWNTHEME     ACRC_IMAGE_AERO_BROWN_PREVIEW
#define RC_IMAGE_CYANTHEME      ACRC_IMAGE_AERO_CYAN_PREVIEW
#define RC_IMAGE_GRAYTHEME      ACRC_IMAGE_AERO_GRAY_PREVIEW
#define RC_IMAGE_GREENTHEME     ACRC_IMAGE_AERO_GREEN_PREVIEW
#define RC_IMAGE_PINKTHEME      ACRC_IMAGE_AERO_PINK_PREVIEW
#define RC_IMAGE_PURPLETHEME    ACRC_IMAGE_AERO_PURPLE_PREVIEW
#define RC_IMAGE_REDTHEME       ACRC_IMAGE_AERO_RED_PREVIEW
#define RC_IMAGE_WHITETHEME     ACRC_IMAGE_AERO_WHITE_PREVIEW
#define RC_IMAGE_YELLOWTHEME    ACRC_IMAGE_AERO_YELLOW_PREVIEW

#define RC_IMAGE_AUTO           RC_IMAGE_NULL
#define RC_IMAGE_DEFAULT        RC_IMAGE_NULL
#define RC_IMAGE_TRANSPARENT    RC_IMAGE_NULL
#define RC_IMAGE_SHADOW         RC_IMAGE_NULL
#define RC_IMAGE_BLUR           RC_IMAGE_NULL

#define RC_IMAGE_HOMEPAGE       RC_IMAGE_NULL

#define RC_IMAGE_NOTHINGAFTERFINISHED RC_IMAGE_NULL
#define RC_IMAGE_SLEEPAFTERFINISHED RC_IMAGE_NULL
#define RC_IMAGE_SHUTDOWNAFTERFINISHED RC_IMAGE_NULL

#define RC_IMAGE_MULTIWINDOW    RC_IMAGE_NULL
#define RC_IMAGE_NEWWINDOW      RC_IMAGE_NULL

#define RC_IMAGE_ASPECTRATIOSTANDARD    RC_IMAGE_NULL
#define RC_IMAGE_ASPECTRATIOWIDESCREEN  RC_IMAGE_NULL

#define RC_IMAGE_ANNOTANALYTICS  RC_IMAGE_NULL
#define RC_IMAGE_AUTOSUBMIT   RC_IMAGE_NULL
#define RC_IMAGE_AUTOSAVEMEDIA RC_IMAGE_NULL
#define RC_IMAGE_SAVEMEDIA    RC_IMAGE_NULL

#define RC_IMAGE_MORE    RC_IMAGE_NULL
#define RC_IMAGE_LESS    RC_IMAGE_NULL

#define RC_IMAGE_RESUMEANNOT  RC_IMAGE_NULL
#define RC_IMAGE_RESETANNOTROTATION  RC_IMAGE_NULL
#define RC_IMAGE_INCREASEANNOTROTATION  RC_IMAGE_NULL
#define RC_IMAGE_DECREASEANNOTROTATION  RC_IMAGE_NULL
#define RC_IMAGE_RESETANNOTSCALE  RC_IMAGE_NULL
#define RC_IMAGE_INCREASEANNOTSCALE  RC_IMAGE_NULL
#define RC_IMAGE_DECREASEANNOTSCALE  RC_IMAGE_NULL
#define RC_IMAGE_RESETANNOTOFFSET  RC_IMAGE_NULL
#define RC_IMAGE_INCREASEANNOTOFFSET  RC_IMAGE_NULL
#define RC_IMAGE_DECREASEANNOTOFFSET  RC_IMAGE_NULL

#define RC_IMAGE_RESET  RC_IMAGE_NULL

#define RC_IMAGE_HUEUP  RC_IMAGE_NULL
#define RC_IMAGE_HUEDOWN  RC_IMAGE_NULL
#define RC_IMAGE_SATURATIONUP  RC_IMAGE_NULL
#define RC_IMAGE_SATURATIONDOWN  RC_IMAGE_NULL
#define RC_IMAGE_GAMMAUP  RC_IMAGE_NULL
#define RC_IMAGE_GAMMADOWN  RC_IMAGE_NULL
#define RC_IMAGE_BRIGHTNESSUP  RC_IMAGE_NULL
#define RC_IMAGE_BRIGHTNESSDOWN  RC_IMAGE_NULL
#define RC_IMAGE_CONTRASTUP  RC_IMAGE_NULL
#define RC_IMAGE_CONTRASTDOWN  RC_IMAGE_NULL

#define RC_IMAGE_LABELPLAYER  RC_IMAGE_NULL
#define RC_IMAGE_OPENDIRECTORY  RC_IMAGE_NULL
#define RC_IMAGE_PREFERLOCALDB  RC_IMAGE_NULL

#define RC_IMAGE_NOAUTOPLAY  RC_IMAGE_NULL
#define RC_IMAGE_AUTOPLAYNEXT  RC_IMAGE_NULL
#define RC_IMAGE_AUTOPLAYCURRENT  RC_IMAGE_NULL

#define RC_IMAGE_PREFERENCES  RC_IMAGE_NULL

#endif // RC_H
