/* ServerSoapServerAgentServiceSoapBindingProxy.h
   Generated by gSOAP 2.8.3 from _serversoap.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef ServerSoapServerAgentServiceSoapBindingProxy_H
#define ServerSoapServerAgentServiceSoapBindingProxy_H
#include "ServerSoapH.h"

namespace ServerSoap {

class SOAP_CMAC ServerAgentServiceSoapBindingProxy : public soap
{ public:
	/// Endpoint URL of service 'ServerAgentServiceSoapBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	ServerAgentServiceSoapBindingProxy();
	/// Constructor with copy of another engine state
	ServerAgentServiceSoapBindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	ServerAgentServiceSoapBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	ServerAgentServiceSoapBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ServerAgentServiceSoapBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ServerAgentServiceSoapBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~ServerAgentServiceSoapBindingProxy();
	/// Initializer used by constructors
	virtual	void ServerAgentServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'blessGameAnnotationWithId' (returns error code or SOAP_OK)
	virtual	int blessGameAnnotationWithId(tns__blessGameAnnotationWithId *tns__blessGameAnnotationWithId_, tns__blessGameAnnotationWithIdResponse *tns__blessGameAnnotationWithIdResponse_) { return blessGameAnnotationWithId(NULL, NULL, tns__blessGameAnnotationWithId_, tns__blessGameAnnotationWithIdResponse_); }
	virtual	int blessGameAnnotationWithId(const char *endpoint, const char *soap_action, tns__blessGameAnnotationWithId *tns__blessGameAnnotationWithId_, tns__blessGameAnnotationWithIdResponse *tns__blessGameAnnotationWithIdResponse_);

	/// Web service operation 'blessMediaAnnotationWithId' (returns error code or SOAP_OK)
	virtual	int blessMediaAnnotationWithId(tns__blessMediaAnnotationWithId *tns__blessMediaAnnotationWithId_, tns__blessMediaAnnotationWithIdResponse *tns__blessMediaAnnotationWithIdResponse_) { return blessMediaAnnotationWithId(NULL, NULL, tns__blessMediaAnnotationWithId_, tns__blessMediaAnnotationWithIdResponse_); }
	virtual	int blessMediaAnnotationWithId(const char *endpoint, const char *soap_action, tns__blessMediaAnnotationWithId *tns__blessMediaAnnotationWithId_, tns__blessMediaAnnotationWithIdResponse *tns__blessMediaAnnotationWithIdResponse_);

	/// Web service operation 'chat' (returns error code or SOAP_OK)
	virtual	int chat(tns__chat *tns__chat_, tns__chatResponse *tns__chatResponse_) { return chat(NULL, NULL, tns__chat_, tns__chatResponse_); }
	virtual	int chat(const char *endpoint, const char *soap_action, tns__chat *tns__chat_, tns__chatResponse *tns__chatResponse_);

	/// Web service operation 'getUser' (returns error code or SOAP_OK)
	virtual	int getUser(tns__getUser *tns__getUser_, tns__getUserResponse *tns__getUserResponse_) { return getUser(NULL, NULL, tns__getUser_, tns__getUserResponse_); }
	virtual	int getUser(const char *endpoint, const char *soap_action, tns__getUser *tns__getUser_, tns__getUserResponse *tns__getUserResponse_);

	/// Web service operation 'isAuthorized' (returns error code or SOAP_OK)
	virtual	int isAuthorized(tns__isAuthorized *tns__isAuthorized_, tns__isAuthorizedResponse *tns__isAuthorizedResponse_) { return isAuthorized(NULL, NULL, tns__isAuthorized_, tns__isAuthorizedResponse_); }
	virtual	int isAuthorized(const char *endpoint, const char *soap_action, tns__isAuthorized *tns__isAuthorized_, tns__isAuthorizedResponse *tns__isAuthorizedResponse_);

	/// Web service operation 'isConnected' (returns error code or SOAP_OK)
	virtual	int isConnected(tns__isConnected *tns__isConnected_, tns__isConnectedResponse *tns__isConnectedResponse_) { return isConnected(NULL, NULL, tns__isConnected_, tns__isConnectedResponse_); }
	virtual	int isConnected(const char *endpoint, const char *soap_action, tns__isConnected *tns__isConnected_, tns__isConnectedResponse *tns__isConnectedResponse_);

	/// Web service operation 'login' (returns error code or SOAP_OK)
	virtual	int login(tns__login *tns__login_, tns__loginResponse *tns__loginResponse_) { return login(NULL, NULL, tns__login_, tns__loginResponse_); }
	virtual	int login(const char *endpoint, const char *soap_action, tns__login *tns__login_, tns__loginResponse *tns__loginResponse_);

	/// Web service operation 'logout' (returns error code or SOAP_OK)
	virtual	int logout(tns__logout *tns__logout_, tns__logoutResponse *tns__logoutResponse_) { return logout(NULL, NULL, tns__logout_, tns__logoutResponse_); }
	virtual	int logout(const char *endpoint, const char *soap_action, tns__logout *tns__logout_, tns__logoutResponse *tns__logoutResponse_);

	/// Web service operation 'selectGameAliasesWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectGameAliasesWithTokenId(tns__selectGameAliasesWithTokenId *tns__selectGameAliasesWithTokenId_, tns__selectGameAliasesWithTokenIdResponse *tns__selectGameAliasesWithTokenIdResponse_) { return selectGameAliasesWithTokenId(NULL, NULL, tns__selectGameAliasesWithTokenId_, tns__selectGameAliasesWithTokenIdResponse_); }
	virtual	int selectGameAliasesWithTokenId(const char *endpoint, const char *soap_action, tns__selectGameAliasesWithTokenId *tns__selectGameAliasesWithTokenId_, tns__selectGameAliasesWithTokenIdResponse *tns__selectGameAliasesWithTokenIdResponse_);

	/// Web service operation 'selectGameAnnotationsWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectGameAnnotationsWithTokenId(tns__selectGameAnnotationsWithTokenId *tns__selectGameAnnotationsWithTokenId_, tns__selectGameAnnotationsWithTokenIdResponse *tns__selectGameAnnotationsWithTokenIdResponse_) { return selectGameAnnotationsWithTokenId(NULL, NULL, tns__selectGameAnnotationsWithTokenId_, tns__selectGameAnnotationsWithTokenIdResponse_); }
	virtual	int selectGameAnnotationsWithTokenId(const char *endpoint, const char *soap_action, tns__selectGameAnnotationsWithTokenId *tns__selectGameAnnotationsWithTokenId_, tns__selectGameAnnotationsWithTokenIdResponse *tns__selectGameAnnotationsWithTokenIdResponse_);

	/// Web service operation 'selectGameTokenWithDigest' (returns error code or SOAP_OK)
	virtual	int selectGameTokenWithDigest(tns__selectGameTokenWithDigest *tns__selectGameTokenWithDigest_, tns__selectGameTokenWithDigestResponse *tns__selectGameTokenWithDigestResponse_) { return selectGameTokenWithDigest(NULL, NULL, tns__selectGameTokenWithDigest_, tns__selectGameTokenWithDigestResponse_); }
	virtual	int selectGameTokenWithDigest(const char *endpoint, const char *soap_action, tns__selectGameTokenWithDigest *tns__selectGameTokenWithDigest_, tns__selectGameTokenWithDigestResponse *tns__selectGameTokenWithDigestResponse_);

	/// Web service operation 'selectGameTokenWithId' (returns error code or SOAP_OK)
	virtual	int selectGameTokenWithId(tns__selectGameTokenWithId *tns__selectGameTokenWithId_, tns__selectGameTokenWithIdResponse *tns__selectGameTokenWithIdResponse_) { return selectGameTokenWithId(NULL, NULL, tns__selectGameTokenWithId_, tns__selectGameTokenWithIdResponse_); }
	virtual	int selectGameTokenWithId(const char *endpoint, const char *soap_action, tns__selectGameTokenWithId *tns__selectGameTokenWithId_, tns__selectGameTokenWithIdResponse *tns__selectGameTokenWithIdResponse_);

	/// Web service operation 'selectMediaAliasesWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectMediaAliasesWithTokenId(tns__selectMediaAliasesWithTokenId *tns__selectMediaAliasesWithTokenId_, tns__selectMediaAliasesWithTokenIdResponse *tns__selectMediaAliasesWithTokenIdResponse_) { return selectMediaAliasesWithTokenId(NULL, NULL, tns__selectMediaAliasesWithTokenId_, tns__selectMediaAliasesWithTokenIdResponse_); }
	virtual	int selectMediaAliasesWithTokenId(const char *endpoint, const char *soap_action, tns__selectMediaAliasesWithTokenId *tns__selectMediaAliasesWithTokenId_, tns__selectMediaAliasesWithTokenIdResponse *tns__selectMediaAliasesWithTokenIdResponse_);

	/// Web service operation 'selectMediaAnnotationsWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectMediaAnnotationsWithTokenId(tns__selectMediaAnnotationsWithTokenId *tns__selectMediaAnnotationsWithTokenId_, tns__selectMediaAnnotationsWithTokenIdResponse *tns__selectMediaAnnotationsWithTokenIdResponse_) { return selectMediaAnnotationsWithTokenId(NULL, NULL, tns__selectMediaAnnotationsWithTokenId_, tns__selectMediaAnnotationsWithTokenIdResponse_); }
	virtual	int selectMediaAnnotationsWithTokenId(const char *endpoint, const char *soap_action, tns__selectMediaAnnotationsWithTokenId *tns__selectMediaAnnotationsWithTokenId_, tns__selectMediaAnnotationsWithTokenIdResponse *tns__selectMediaAnnotationsWithTokenIdResponse_);

	/// Web service operation 'selectMediaTokenWithDigest' (returns error code or SOAP_OK)
	virtual	int selectMediaTokenWithDigest(tns__selectMediaTokenWithDigest *tns__selectMediaTokenWithDigest_, tns__selectMediaTokenWithDigestResponse *tns__selectMediaTokenWithDigestResponse_) { return selectMediaTokenWithDigest(NULL, NULL, tns__selectMediaTokenWithDigest_, tns__selectMediaTokenWithDigestResponse_); }
	virtual	int selectMediaTokenWithDigest(const char *endpoint, const char *soap_action, tns__selectMediaTokenWithDigest *tns__selectMediaTokenWithDigest_, tns__selectMediaTokenWithDigestResponse *tns__selectMediaTokenWithDigestResponse_);

	/// Web service operation 'selectMediaTokenWithId' (returns error code or SOAP_OK)
	virtual	int selectMediaTokenWithId(tns__selectMediaTokenWithId *tns__selectMediaTokenWithId_, tns__selectMediaTokenWithIdResponse *tns__selectMediaTokenWithIdResponse_) { return selectMediaTokenWithId(NULL, NULL, tns__selectMediaTokenWithId_, tns__selectMediaTokenWithIdResponse_); }
	virtual	int selectMediaTokenWithId(const char *endpoint, const char *soap_action, tns__selectMediaTokenWithId *tns__selectMediaTokenWithId_, tns__selectMediaTokenWithIdResponse *tns__selectMediaTokenWithIdResponse_);

	/// Web service operation 'selectRelatedGameAnnotationsWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectRelatedGameAnnotationsWithTokenId(tns__selectRelatedGameAnnotationsWithTokenId *tns__selectRelatedGameAnnotationsWithTokenId_, tns__selectRelatedGameAnnotationsWithTokenIdResponse *tns__selectRelatedGameAnnotationsWithTokenIdResponse_) { return selectRelatedGameAnnotationsWithTokenId(NULL, NULL, tns__selectRelatedGameAnnotationsWithTokenId_, tns__selectRelatedGameAnnotationsWithTokenIdResponse_); }
	virtual	int selectRelatedGameAnnotationsWithTokenId(const char *endpoint, const char *soap_action, tns__selectRelatedGameAnnotationsWithTokenId *tns__selectRelatedGameAnnotationsWithTokenId_, tns__selectRelatedGameAnnotationsWithTokenIdResponse *tns__selectRelatedGameAnnotationsWithTokenIdResponse_);

	/// Web service operation 'selectRelatedMediaAnnotationsWithTokenId' (returns error code or SOAP_OK)
	virtual	int selectRelatedMediaAnnotationsWithTokenId(tns__selectRelatedMediaAnnotationsWithTokenId *tns__selectRelatedMediaAnnotationsWithTokenId_, tns__selectRelatedMediaAnnotationsWithTokenIdResponse *tns__selectRelatedMediaAnnotationsWithTokenIdResponse_) { return selectRelatedMediaAnnotationsWithTokenId(NULL, NULL, tns__selectRelatedMediaAnnotationsWithTokenId_, tns__selectRelatedMediaAnnotationsWithTokenIdResponse_); }
	virtual	int selectRelatedMediaAnnotationsWithTokenId(const char *endpoint, const char *soap_action, tns__selectRelatedMediaAnnotationsWithTokenId *tns__selectRelatedMediaAnnotationsWithTokenId_, tns__selectRelatedMediaAnnotationsWithTokenIdResponse *tns__selectRelatedMediaAnnotationsWithTokenIdResponse_);

	/// Web service operation 'setCallback' (returns error code or SOAP_OK)
	virtual	int setCallback(tns__setCallback *tns__setCallback_, tns__setCallbackResponse *tns__setCallbackResponse_) { return setCallback(NULL, NULL, tns__setCallback_, tns__setCallbackResponse_); }
	virtual	int setCallback(const char *endpoint, const char *soap_action, tns__setCallback *tns__setCallback_, tns__setCallbackResponse *tns__setCallbackResponse_);

	/// Web service operation 'setClientType' (returns error code or SOAP_OK)
	virtual	int setClientType(tns__setClientType *tns__setClientType_, tns__setClientTypeResponse *tns__setClientTypeResponse_) { return setClientType(NULL, NULL, tns__setClientType_, tns__setClientTypeResponse_); }
	virtual	int setClientType(const char *endpoint, const char *soap_action, tns__setClientType *tns__setClientType_, tns__setClientTypeResponse *tns__setClientTypeResponse_);

	/// Web service operation 'setUserAnonymous' (returns error code or SOAP_OK)
	virtual	int setUserAnonymous(tns__setUserAnonymous *tns__setUserAnonymous_, tns__setUserAnonymousResponse *tns__setUserAnonymousResponse_) { return setUserAnonymous(NULL, NULL, tns__setUserAnonymous_, tns__setUserAnonymousResponse_); }
	virtual	int setUserAnonymous(const char *endpoint, const char *soap_action, tns__setUserAnonymous *tns__setUserAnonymous_, tns__setUserAnonymousResponse *tns__setUserAnonymousResponse_);

	/// Web service operation 'setUserLanguage' (returns error code or SOAP_OK)
	virtual	int setUserLanguage(tns__setUserLanguage *tns__setUserLanguage_, tns__setUserLanguageResponse *tns__setUserLanguageResponse_) { return setUserLanguage(NULL, NULL, tns__setUserLanguage_, tns__setUserLanguageResponse_); }
	virtual	int setUserLanguage(const char *endpoint, const char *soap_action, tns__setUserLanguage *tns__setUserLanguage_, tns__setUserLanguageResponse *tns__setUserLanguageResponse_);

	/// Web service operation 'submitGameAlias' (returns error code or SOAP_OK)
	virtual	int submitGameAlias(tns__submitGameAlias *tns__submitGameAlias_, tns__submitGameAliasResponse *tns__submitGameAliasResponse_) { return submitGameAlias(NULL, NULL, tns__submitGameAlias_, tns__submitGameAliasResponse_); }
	virtual	int submitGameAlias(const char *endpoint, const char *soap_action, tns__submitGameAlias *tns__submitGameAlias_, tns__submitGameAliasResponse *tns__submitGameAliasResponse_);

	/// Web service operation 'submitGameAliasTextAndTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitGameAliasTextAndTokenDigest(tns__submitGameAliasTextAndTokenDigest *tns__submitGameAliasTextAndTokenDigest_, tns__submitGameAliasTextAndTokenDigestResponse *tns__submitGameAliasTextAndTokenDigestResponse_) { return submitGameAliasTextAndTokenDigest(NULL, NULL, tns__submitGameAliasTextAndTokenDigest_, tns__submitGameAliasTextAndTokenDigestResponse_); }
	virtual	int submitGameAliasTextAndTokenDigest(const char *endpoint, const char *soap_action, tns__submitGameAliasTextAndTokenDigest *tns__submitGameAliasTextAndTokenDigest_, tns__submitGameAliasTextAndTokenDigestResponse *tns__submitGameAliasTextAndTokenDigestResponse_);

	/// Web service operation 'submitGameAliasTextWithTokenId' (returns error code or SOAP_OK)
	virtual	int submitGameAliasTextWithTokenId(tns__submitGameAliasTextWithTokenId *tns__submitGameAliasTextWithTokenId_, tns__submitGameAliasTextWithTokenIdResponse *tns__submitGameAliasTextWithTokenIdResponse_) { return submitGameAliasTextWithTokenId(NULL, NULL, tns__submitGameAliasTextWithTokenId_, tns__submitGameAliasTextWithTokenIdResponse_); }
	virtual	int submitGameAliasTextWithTokenId(const char *endpoint, const char *soap_action, tns__submitGameAliasTextWithTokenId *tns__submitGameAliasTextWithTokenId_, tns__submitGameAliasTextWithTokenIdResponse *tns__submitGameAliasTextWithTokenIdResponse_);

	/// Web service operation 'submitGameAnnotation' (returns error code or SOAP_OK)
	virtual	int submitGameAnnotation(tns__submitGameAnnotation *tns__submitGameAnnotation_, tns__submitGameAnnotationResponse *tns__submitGameAnnotationResponse_) { return submitGameAnnotation(NULL, NULL, tns__submitGameAnnotation_, tns__submitGameAnnotationResponse_); }
	virtual	int submitGameAnnotation(const char *endpoint, const char *soap_action, tns__submitGameAnnotation *tns__submitGameAnnotation_, tns__submitGameAnnotationResponse *tns__submitGameAnnotationResponse_);

	/// Web service operation 'submitGameAnnotationTextAndTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitGameAnnotationTextAndTokenDigest(tns__submitGameAnnotationTextAndTokenDigest *tns__submitGameAnnotationTextAndTokenDigest_, tns__submitGameAnnotationTextAndTokenDigestResponse *tns__submitGameAnnotationTextAndTokenDigestResponse_) { return submitGameAnnotationTextAndTokenDigest(NULL, NULL, tns__submitGameAnnotationTextAndTokenDigest_, tns__submitGameAnnotationTextAndTokenDigestResponse_); }
	virtual	int submitGameAnnotationTextAndTokenDigest(const char *endpoint, const char *soap_action, tns__submitGameAnnotationTextAndTokenDigest *tns__submitGameAnnotationTextAndTokenDigest_, tns__submitGameAnnotationTextAndTokenDigestResponse *tns__submitGameAnnotationTextAndTokenDigestResponse_);

	/// Web service operation 'submitGameAnnotationTextWithTokenId' (returns error code or SOAP_OK)
	virtual	int submitGameAnnotationTextWithTokenId(tns__submitGameAnnotationTextWithTokenId *tns__submitGameAnnotationTextWithTokenId_, tns__submitGameAnnotationTextWithTokenIdResponse *tns__submitGameAnnotationTextWithTokenIdResponse_) { return submitGameAnnotationTextWithTokenId(NULL, NULL, tns__submitGameAnnotationTextWithTokenId_, tns__submitGameAnnotationTextWithTokenIdResponse_); }
	virtual	int submitGameAnnotationTextWithTokenId(const char *endpoint, const char *soap_action, tns__submitGameAnnotationTextWithTokenId *tns__submitGameAnnotationTextWithTokenId_, tns__submitGameAnnotationTextWithTokenIdResponse *tns__submitGameAnnotationTextWithTokenIdResponse_);

	/// Web service operation 'submitGameToken' (returns error code or SOAP_OK)
	virtual	int submitGameToken(tns__submitGameToken *tns__submitGameToken_, tns__submitGameTokenResponse *tns__submitGameTokenResponse_) { return submitGameToken(NULL, NULL, tns__submitGameToken_, tns__submitGameTokenResponse_); }
	virtual	int submitGameToken(const char *endpoint, const char *soap_action, tns__submitGameToken *tns__submitGameToken_, tns__submitGameTokenResponse *tns__submitGameTokenResponse_);

	/// Web service operation 'submitGameTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitGameTokenDigest(tns__submitGameTokenDigest *tns__submitGameTokenDigest_, tns__submitGameTokenDigestResponse *tns__submitGameTokenDigestResponse_) { return submitGameTokenDigest(NULL, NULL, tns__submitGameTokenDigest_, tns__submitGameTokenDigestResponse_); }
	virtual	int submitGameTokenDigest(const char *endpoint, const char *soap_action, tns__submitGameTokenDigest *tns__submitGameTokenDigest_, tns__submitGameTokenDigestResponse *tns__submitGameTokenDigestResponse_);

	/// Web service operation 'submitMediaAlias' (returns error code or SOAP_OK)
	virtual	int submitMediaAlias(tns__submitMediaAlias *tns__submitMediaAlias_, tns__submitMediaAliasResponse *tns__submitMediaAliasResponse_) { return submitMediaAlias(NULL, NULL, tns__submitMediaAlias_, tns__submitMediaAliasResponse_); }
	virtual	int submitMediaAlias(const char *endpoint, const char *soap_action, tns__submitMediaAlias *tns__submitMediaAlias_, tns__submitMediaAliasResponse *tns__submitMediaAliasResponse_);

	/// Web service operation 'submitMediaAliasTextAndTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitMediaAliasTextAndTokenDigest(tns__submitMediaAliasTextAndTokenDigest *tns__submitMediaAliasTextAndTokenDigest_, tns__submitMediaAliasTextAndTokenDigestResponse *tns__submitMediaAliasTextAndTokenDigestResponse_) { return submitMediaAliasTextAndTokenDigest(NULL, NULL, tns__submitMediaAliasTextAndTokenDigest_, tns__submitMediaAliasTextAndTokenDigestResponse_); }
	virtual	int submitMediaAliasTextAndTokenDigest(const char *endpoint, const char *soap_action, tns__submitMediaAliasTextAndTokenDigest *tns__submitMediaAliasTextAndTokenDigest_, tns__submitMediaAliasTextAndTokenDigestResponse *tns__submitMediaAliasTextAndTokenDigestResponse_);

	/// Web service operation 'submitMediaAliasTextWithTokenId' (returns error code or SOAP_OK)
	virtual	int submitMediaAliasTextWithTokenId(tns__submitMediaAliasTextWithTokenId *tns__submitMediaAliasTextWithTokenId_, tns__submitMediaAliasTextWithTokenIdResponse *tns__submitMediaAliasTextWithTokenIdResponse_) { return submitMediaAliasTextWithTokenId(NULL, NULL, tns__submitMediaAliasTextWithTokenId_, tns__submitMediaAliasTextWithTokenIdResponse_); }
	virtual	int submitMediaAliasTextWithTokenId(const char *endpoint, const char *soap_action, tns__submitMediaAliasTextWithTokenId *tns__submitMediaAliasTextWithTokenId_, tns__submitMediaAliasTextWithTokenIdResponse *tns__submitMediaAliasTextWithTokenIdResponse_);

	/// Web service operation 'submitMediaAnnotation' (returns error code or SOAP_OK)
	virtual	int submitMediaAnnotation(tns__submitMediaAnnotation *tns__submitMediaAnnotation_, tns__submitMediaAnnotationResponse *tns__submitMediaAnnotationResponse_) { return submitMediaAnnotation(NULL, NULL, tns__submitMediaAnnotation_, tns__submitMediaAnnotationResponse_); }
	virtual	int submitMediaAnnotation(const char *endpoint, const char *soap_action, tns__submitMediaAnnotation *tns__submitMediaAnnotation_, tns__submitMediaAnnotationResponse *tns__submitMediaAnnotationResponse_);

	/// Web service operation 'submitMediaAnnotationTextAndTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitMediaAnnotationTextAndTokenDigest(tns__submitMediaAnnotationTextAndTokenDigest *tns__submitMediaAnnotationTextAndTokenDigest_, tns__submitMediaAnnotationTextAndTokenDigestResponse *tns__submitMediaAnnotationTextAndTokenDigestResponse_) { return submitMediaAnnotationTextAndTokenDigest(NULL, NULL, tns__submitMediaAnnotationTextAndTokenDigest_, tns__submitMediaAnnotationTextAndTokenDigestResponse_); }
	virtual	int submitMediaAnnotationTextAndTokenDigest(const char *endpoint, const char *soap_action, tns__submitMediaAnnotationTextAndTokenDigest *tns__submitMediaAnnotationTextAndTokenDigest_, tns__submitMediaAnnotationTextAndTokenDigestResponse *tns__submitMediaAnnotationTextAndTokenDigestResponse_);

	/// Web service operation 'submitMediaAnnotationTextWithTokenId' (returns error code or SOAP_OK)
	virtual	int submitMediaAnnotationTextWithTokenId(tns__submitMediaAnnotationTextWithTokenId *tns__submitMediaAnnotationTextWithTokenId_, tns__submitMediaAnnotationTextWithTokenIdResponse *tns__submitMediaAnnotationTextWithTokenIdResponse_) { return submitMediaAnnotationTextWithTokenId(NULL, NULL, tns__submitMediaAnnotationTextWithTokenId_, tns__submitMediaAnnotationTextWithTokenIdResponse_); }
	virtual	int submitMediaAnnotationTextWithTokenId(const char *endpoint, const char *soap_action, tns__submitMediaAnnotationTextWithTokenId *tns__submitMediaAnnotationTextWithTokenId_, tns__submitMediaAnnotationTextWithTokenIdResponse *tns__submitMediaAnnotationTextWithTokenIdResponse_);

	/// Web service operation 'submitMediaToken' (returns error code or SOAP_OK)
	virtual	int submitMediaToken(tns__submitMediaToken *tns__submitMediaToken_, tns__submitMediaTokenResponse *tns__submitMediaTokenResponse_) { return submitMediaToken(NULL, NULL, tns__submitMediaToken_, tns__submitMediaTokenResponse_); }
	virtual	int submitMediaToken(const char *endpoint, const char *soap_action, tns__submitMediaToken *tns__submitMediaToken_, tns__submitMediaTokenResponse *tns__submitMediaTokenResponse_);

	/// Web service operation 'submitMediaTokenDigest' (returns error code or SOAP_OK)
	virtual	int submitMediaTokenDigest(tns__submitMediaTokenDigest *tns__submitMediaTokenDigest_, tns__submitMediaTokenDigestResponse *tns__submitMediaTokenDigestResponse_) { return submitMediaTokenDigest(NULL, NULL, tns__submitMediaTokenDigest_, tns__submitMediaTokenDigestResponse_); }
	virtual	int submitMediaTokenDigest(const char *endpoint, const char *soap_action, tns__submitMediaTokenDigest *tns__submitMediaTokenDigest_, tns__submitMediaTokenDigestResponse *tns__submitMediaTokenDigestResponse_);

	/// Web service operation 'updateGameAnnotationTextWithId' (returns error code or SOAP_OK)
	virtual	int updateGameAnnotationTextWithId(tns__updateGameAnnotationTextWithId *tns__updateGameAnnotationTextWithId_, tns__updateGameAnnotationTextWithIdResponse *tns__updateGameAnnotationTextWithIdResponse_) { return updateGameAnnotationTextWithId(NULL, NULL, tns__updateGameAnnotationTextWithId_, tns__updateGameAnnotationTextWithIdResponse_); }
	virtual	int updateGameAnnotationTextWithId(const char *endpoint, const char *soap_action, tns__updateGameAnnotationTextWithId *tns__updateGameAnnotationTextWithId_, tns__updateGameAnnotationTextWithIdResponse *tns__updateGameAnnotationTextWithIdResponse_);

	/// Web service operation 'updateMediaAnnotationTextWithId' (returns error code or SOAP_OK)
	virtual	int updateMediaAnnotationTextWithId(tns__updateMediaAnnotationTextWithId *tns__updateMediaAnnotationTextWithId_, tns__updateMediaAnnotationTextWithIdResponse *tns__updateMediaAnnotationTextWithIdResponse_) { return updateMediaAnnotationTextWithId(NULL, NULL, tns__updateMediaAnnotationTextWithId_, tns__updateMediaAnnotationTextWithIdResponse_); }
	virtual	int updateMediaAnnotationTextWithId(const char *endpoint, const char *soap_action, tns__updateMediaAnnotationTextWithId *tns__updateMediaAnnotationTextWithId_, tns__updateMediaAnnotationTextWithIdResponse *tns__updateMediaAnnotationTextWithIdResponse_);

	/// Web service operation 'visitGameTokenWithId' (returns error code or SOAP_OK)
	virtual	int visitGameTokenWithId(tns__visitGameTokenWithId *tns__visitGameTokenWithId_, tns__visitGameTokenWithIdResponse *tns__visitGameTokenWithIdResponse_) { return visitGameTokenWithId(NULL, NULL, tns__visitGameTokenWithId_, tns__visitGameTokenWithIdResponse_); }
	virtual	int visitGameTokenWithId(const char *endpoint, const char *soap_action, tns__visitGameTokenWithId *tns__visitGameTokenWithId_, tns__visitGameTokenWithIdResponse *tns__visitGameTokenWithIdResponse_);

	/// Web service operation 'visitMediaTokenWithId' (returns error code or SOAP_OK)
	virtual	int visitMediaTokenWithId(tns__visitMediaTokenWithId *tns__visitMediaTokenWithId_, tns__visitMediaTokenWithIdResponse *tns__visitMediaTokenWithIdResponse_) { return visitMediaTokenWithId(NULL, NULL, tns__visitMediaTokenWithId_, tns__visitMediaTokenWithIdResponse_); }
	virtual	int visitMediaTokenWithId(const char *endpoint, const char *soap_action, tns__visitMediaTokenWithId *tns__visitMediaTokenWithId_, tns__visitMediaTokenWithIdResponse *tns__visitMediaTokenWithIdResponse_);
};

} // namespace ServerSoap

#endif
