# soap.pri
# Since 9/10/2011

## TODO: Automatic generate this pri file!!

SERVER_SOAP_BINDING = ServerAgentServiceSoapBinding
SERVER_SOAP_PREFIX = ServerSoap

SERVER_SOAP_HOME=$$PWD/serversoap

INCLUDEPATH += $$PWD
INCLUDEPATH += $$SERVER_SOAP_HOME

HEADERS += \
    $$SERVER_SOAP_HOME/$${SERVER_SOAP_PREFIX}$${SERVER_SOAP_BINDING}Proxy.h \
    $$SERVER_SOAP_HOME/$${SERVER_SOAP_PREFIX}H.h \
    $$SERVER_SOAP_HOME/$${SERVER_SOAP_PREFIX}Stub.h

SOURCES += \
    $$SERVER_SOAP_HOME/$${SERVER_SOAP_PREFIX}C.cpp \
    $$SERVER_SOAP_HOME/$${SERVER_SOAP_PREFIX}Client.cpp
    #$$SERVER_SOAP_HOME/$${SERVER_SOAP_PREFIX}ClientLib.cpp

OTHER_FILES += \
    $$PWD/serversoap.gen.cmd

# EOF
